package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.EvalManagement;
import com.casic.oarp.datavisual.po.EvalManagementExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface EvalManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    long countByExample(EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int deleteByExample(EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int insert(EvalManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int insertSelective(EvalManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    List<EvalManagement> selectByExampleWithBLOBs(EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    List<EvalManagement> selectByExample(EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    EvalManagement selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") EvalManagement record, @Param("example") EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") EvalManagement record, @Param("example") EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int updateByExample(@Param("record") EvalManagement record, @Param("example") EvalManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int updateByPrimaryKeySelective(EvalManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EvalManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management
     *
     * @mbg.generated Sat Oct 27 18:27:26 CST 2018
     */
    int updateByPrimaryKey(EvalManagement record);
}