package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.EvalImperfection;
import com.casic.oarp.datavisual.po.EvalImperfectionExample;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface EvalImperfectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    long countByExample(EvalImperfectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int deleteByExample(EvalImperfectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int insert(EvalImperfection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int insertSelective(EvalImperfection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    List<EvalImperfection> selectByExample(EvalImperfectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    EvalImperfection selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") EvalImperfection record, @Param("example") EvalImperfectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int updateByExample(@Param("record") EvalImperfection record, @Param("example") EvalImperfectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int updateByPrimaryKeySelective(EvalImperfection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eval_imperfection
     *
     * @mbg.generated Thu Oct 25 17:18:02 CST 2018
     */
    int updateByPrimaryKey(EvalImperfection record);
}