package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.EvalManagementScore;
import com.casic.oarp.datavisual.po.EvalManagementScoreExample;
import com.casic.oarp.datavisual.po.EvalManagementScoreWithBLOBs;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface EvalManagementScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    long countByExample(EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int deleteByExample(EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int insert(EvalManagementScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int insertSelective(EvalManagementScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    List<EvalManagementScoreWithBLOBs> selectByExampleWithBLOBs(EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    List<EvalManagementScore> selectByExample(EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    EvalManagementScoreWithBLOBs selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") EvalManagementScoreWithBLOBs record, @Param("example") EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") EvalManagementScoreWithBLOBs record, @Param("example") EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int updateByExample(@Param("record") EvalManagementScore record, @Param("example") EvalManagementScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int updateByPrimaryKeySelective(EvalManagementScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(EvalManagementScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    int updateByPrimaryKey(EvalManagementScore record);
}