package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.HtywOrgization;
import com.casic.oarp.datavisual.po.HtywOrgizationExample;
import com.casic.oarp.datavisual.po.HtywOrgizationWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface HtywOrgizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    long countByExample(HtywOrgizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    int deleteByExample(HtywOrgizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    int insert(HtywOrgizationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    int insertSelective(HtywOrgizationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    List<HtywOrgizationWithBLOBs> selectByExampleWithBLOBs(HtywOrgizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    List<HtywOrgization> selectByExample(HtywOrgizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") HtywOrgizationWithBLOBs record, @Param("example") HtywOrgizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") HtywOrgizationWithBLOBs record, @Param("example") HtywOrgizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    int updateByExample(@Param("record") HtywOrgization record, @Param("example") HtywOrgizationExample example);
}