package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.ScCreditFivescore;
import com.casic.oarp.datavisual.po.ScCreditFivescoreExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ScCreditFivescoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    long countByExample(ScCreditFivescoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int deleteByExample(ScCreditFivescoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int deleteByPrimaryKey(String scCreditFivescoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int insert(ScCreditFivescore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int insertSelective(ScCreditFivescore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    List<ScCreditFivescore> selectByExample(ScCreditFivescoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    ScCreditFivescore selectByPrimaryKey(String scCreditFivescoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") ScCreditFivescore record, @Param("example") ScCreditFivescoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int updateByExample(@Param("record") ScCreditFivescore record, @Param("example") ScCreditFivescoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int updateByPrimaryKeySelective(ScCreditFivescore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    int updateByPrimaryKey(ScCreditFivescore record);
}