package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.ScCreditQuant;
import com.casic.oarp.datavisual.po.ScCreditQuantExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ScCreditQuantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    long countByExample(ScCreditQuantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int deleteByExample(ScCreditQuantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int deleteByPrimaryKey(String scCreditQuantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int insert(ScCreditQuant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int insertSelective(ScCreditQuant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    List<ScCreditQuant> selectByExample(ScCreditQuantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    ScCreditQuant selectByPrimaryKey(String scCreditQuantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") ScCreditQuant record, @Param("example") ScCreditQuantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int updateByExample(@Param("record") ScCreditQuant record, @Param("example") ScCreditQuantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int updateByPrimaryKeySelective(ScCreditQuant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_quant
     *
     * @mbg.generated Mon Nov 19 10:32:56 CST 2018
     */
    int updateByPrimaryKey(ScCreditQuant record);
}