package com.casic.oarp.datavisual.mapper;

import com.casic.oarp.datavisual.po.Scwarns;
import com.casic.oarp.datavisual.po.ScwarnsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ScwarnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    long countByExample(ScwarnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int deleteByExample(ScwarnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int deleteByPrimaryKey(String warnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int insert(Scwarns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int insertSelective(Scwarns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    List<Scwarns> selectByExample(ScwarnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    Scwarns selectByPrimaryKey(String warnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") Scwarns record, @Param("example") ScwarnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int updateByExample(@Param("record") Scwarns record, @Param("example") ScwarnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int updateByPrimaryKeySelective(Scwarns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    int updateByPrimaryKey(Scwarns record);
}