package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;

public class EvalManagement implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.id
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.ref_sheetid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal refSheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.code
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.name
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.corpid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal corpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.status
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.descr_name
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String descrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.create_userid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.create_username
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String createUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.createdate
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.version
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.parentid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.rootid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal rootid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.catalogids
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String catalogids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.eval_type
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String evalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.total
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.evallelvel
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String evallelvel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.evalgrade
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String evalgrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.evaldept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String evaldept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.dept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.evaldeptid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private BigDecimal evaldeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.score
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.score1
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.score2
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.score3
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String score3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.score4
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String score4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.updept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String updept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.updept1
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String updept1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management.descr
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_eval_management
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.id
     *
     * @return the value of fx_eval_management.id
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.id
     *
     * @param id the value for fx_eval_management.id
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.ref_sheetid
     *
     * @return the value of fx_eval_management.ref_sheetid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getRefSheetid() {
        return refSheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.ref_sheetid
     *
     * @param refSheetid the value for fx_eval_management.ref_sheetid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setRefSheetid(BigDecimal refSheetid) {
        this.refSheetid = refSheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.code
     *
     * @return the value of fx_eval_management.code
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.code
     *
     * @param code the value for fx_eval_management.code
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.name
     *
     * @return the value of fx_eval_management.name
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.name
     *
     * @param name the value for fx_eval_management.name
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.corpid
     *
     * @return the value of fx_eval_management.corpid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getCorpid() {
        return corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.corpid
     *
     * @param corpid the value for fx_eval_management.corpid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setCorpid(BigDecimal corpid) {
        this.corpid = corpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.status
     *
     * @return the value of fx_eval_management.status
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.status
     *
     * @param status the value for fx_eval_management.status
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.descr_name
     *
     * @return the value of fx_eval_management.descr_name
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getDescrName() {
        return descrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.descr_name
     *
     * @param descrName the value for fx_eval_management.descr_name
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setDescrName(String descrName) {
        this.descrName = descrName == null ? null : descrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.create_userid
     *
     * @return the value of fx_eval_management.create_userid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.create_userid
     *
     * @param createUserid the value for fx_eval_management.create_userid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setCreateUserid(BigDecimal createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.create_username
     *
     * @return the value of fx_eval_management.create_username
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.create_username
     *
     * @param createUsername the value for fx_eval_management.create_username
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.createdate
     *
     * @return the value of fx_eval_management.createdate
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.createdate
     *
     * @param createdate the value for fx_eval_management.createdate
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.version
     *
     * @return the value of fx_eval_management.version
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.version
     *
     * @param version the value for fx_eval_management.version
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.parentid
     *
     * @return the value of fx_eval_management.parentid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.parentid
     *
     * @param parentid the value for fx_eval_management.parentid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setParentid(BigDecimal parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.rootid
     *
     * @return the value of fx_eval_management.rootid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getRootid() {
        return rootid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.rootid
     *
     * @param rootid the value for fx_eval_management.rootid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setRootid(BigDecimal rootid) {
        this.rootid = rootid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.catalogids
     *
     * @return the value of fx_eval_management.catalogids
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getCatalogids() {
        return catalogids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.catalogids
     *
     * @param catalogids the value for fx_eval_management.catalogids
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setCatalogids(String catalogids) {
        this.catalogids = catalogids == null ? null : catalogids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.eval_type
     *
     * @return the value of fx_eval_management.eval_type
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getEvalType() {
        return evalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.eval_type
     *
     * @param evalType the value for fx_eval_management.eval_type
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setEvalType(String evalType) {
        this.evalType = evalType == null ? null : evalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.total
     *
     * @return the value of fx_eval_management.total
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.total
     *
     * @param total the value for fx_eval_management.total
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setTotal(String total) {
        this.total = total == null ? null : total.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.evallelvel
     *
     * @return the value of fx_eval_management.evallelvel
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getEvallelvel() {
        return evallelvel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.evallelvel
     *
     * @param evallelvel the value for fx_eval_management.evallelvel
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setEvallelvel(String evallelvel) {
        this.evallelvel = evallelvel == null ? null : evallelvel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.evalgrade
     *
     * @return the value of fx_eval_management.evalgrade
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getEvalgrade() {
        return evalgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.evalgrade
     *
     * @param evalgrade the value for fx_eval_management.evalgrade
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setEvalgrade(String evalgrade) {
        this.evalgrade = evalgrade == null ? null : evalgrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.evaldept
     *
     * @return the value of fx_eval_management.evaldept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getEvaldept() {
        return evaldept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.evaldept
     *
     * @param evaldept the value for fx_eval_management.evaldept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setEvaldept(String evaldept) {
        this.evaldept = evaldept == null ? null : evaldept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.dept
     *
     * @return the value of fx_eval_management.dept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.dept
     *
     * @param dept the value for fx_eval_management.dept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.evaldeptid
     *
     * @return the value of fx_eval_management.evaldeptid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public BigDecimal getEvaldeptid() {
        return evaldeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.evaldeptid
     *
     * @param evaldeptid the value for fx_eval_management.evaldeptid
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setEvaldeptid(BigDecimal evaldeptid) {
        this.evaldeptid = evaldeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.score
     *
     * @return the value of fx_eval_management.score
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.score
     *
     * @param score the value for fx_eval_management.score
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.score1
     *
     * @return the value of fx_eval_management.score1
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.score1
     *
     * @param score1 the value for fx_eval_management.score1
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setScore1(String score1) {
        this.score1 = score1 == null ? null : score1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.score2
     *
     * @return the value of fx_eval_management.score2
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.score2
     *
     * @param score2 the value for fx_eval_management.score2
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setScore2(String score2) {
        this.score2 = score2 == null ? null : score2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.score3
     *
     * @return the value of fx_eval_management.score3
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getScore3() {
        return score3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.score3
     *
     * @param score3 the value for fx_eval_management.score3
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setScore3(String score3) {
        this.score3 = score3 == null ? null : score3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.score4
     *
     * @return the value of fx_eval_management.score4
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getScore4() {
        return score4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.score4
     *
     * @param score4 the value for fx_eval_management.score4
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setScore4(String score4) {
        this.score4 = score4 == null ? null : score4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.updept
     *
     * @return the value of fx_eval_management.updept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getUpdept() {
        return updept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.updept
     *
     * @param updept the value for fx_eval_management.updept
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setUpdept(String updept) {
        this.updept = updept == null ? null : updept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.updept1
     *
     * @return the value of fx_eval_management.updept1
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getUpdept1() {
        return updept1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.updept1
     *
     * @param updept1 the value for fx_eval_management.updept1
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setUpdept1(String updept1) {
        this.updept1 = updept1 == null ? null : updept1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management.descr
     *
     * @return the value of fx_eval_management.descr
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management.descr
     *
     * @param descr the value for fx_eval_management.descr
     *
     * @mbg.generated Tue Oct 30 09:56:15 CST 2018
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }
}