package com.casic.oarp.datavisual.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class EvalManagementScoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public EvalManagementScoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(String value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(String value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(String value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(String value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(String value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLike(String value) {
            addCriterion("score like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotLike(String value) {
            addCriterion("score not like", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<String> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<String> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(String value1, String value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(String value1, String value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andManagementidIsNull() {
            addCriterion("managementid is null");
            return (Criteria) this;
        }

        public Criteria andManagementidIsNotNull() {
            addCriterion("managementid is not null");
            return (Criteria) this;
        }

        public Criteria andManagementidEqualTo(BigDecimal value) {
            addCriterion("managementid =", value, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidNotEqualTo(BigDecimal value) {
            addCriterion("managementid <>", value, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidGreaterThan(BigDecimal value) {
            addCriterion("managementid >", value, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("managementid >=", value, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidLessThan(BigDecimal value) {
            addCriterion("managementid <", value, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("managementid <=", value, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidIn(List<BigDecimal> values) {
            addCriterion("managementid in", values, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidNotIn(List<BigDecimal> values) {
            addCriterion("managementid not in", values, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("managementid between", value1, value2, "managementid");
            return (Criteria) this;
        }

        public Criteria andManagementidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("managementid not between", value1, value2, "managementid");
            return (Criteria) this;
        }

        public Criteria andCatalogidIsNull() {
            addCriterion("catalogid is null");
            return (Criteria) this;
        }

        public Criteria andCatalogidIsNotNull() {
            addCriterion("catalogid is not null");
            return (Criteria) this;
        }

        public Criteria andCatalogidEqualTo(BigDecimal value) {
            addCriterion("catalogid =", value, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidNotEqualTo(BigDecimal value) {
            addCriterion("catalogid <>", value, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidGreaterThan(BigDecimal value) {
            addCriterion("catalogid >", value, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("catalogid >=", value, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidLessThan(BigDecimal value) {
            addCriterion("catalogid <", value, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("catalogid <=", value, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidIn(List<BigDecimal> values) {
            addCriterion("catalogid in", values, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidNotIn(List<BigDecimal> values) {
            addCriterion("catalogid not in", values, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("catalogid between", value1, value2, "catalogid");
            return (Criteria) this;
        }

        public Criteria andCatalogidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("catalogid not between", value1, value2, "catalogid");
            return (Criteria) this;
        }

        public Criteria andStandscoreIsNull() {
            addCriterion("standscore is null");
            return (Criteria) this;
        }

        public Criteria andStandscoreIsNotNull() {
            addCriterion("standscore is not null");
            return (Criteria) this;
        }

        public Criteria andStandscoreEqualTo(String value) {
            addCriterion("standscore =", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreNotEqualTo(String value) {
            addCriterion("standscore <>", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreGreaterThan(String value) {
            addCriterion("standscore >", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreGreaterThanOrEqualTo(String value) {
            addCriterion("standscore >=", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreLessThan(String value) {
            addCriterion("standscore <", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreLessThanOrEqualTo(String value) {
            addCriterion("standscore <=", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreLike(String value) {
            addCriterion("standscore like", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreNotLike(String value) {
            addCriterion("standscore not like", value, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreIn(List<String> values) {
            addCriterion("standscore in", values, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreNotIn(List<String> values) {
            addCriterion("standscore not in", values, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreBetween(String value1, String value2) {
            addCriterion("standscore between", value1, value2, "standscore");
            return (Criteria) this;
        }

        public Criteria andStandscoreNotBetween(String value1, String value2) {
            addCriterion("standscore not between", value1, value2, "standscore");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(BigDecimal value) {
            addCriterion("seq =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(BigDecimal value) {
            addCriterion("seq <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(BigDecimal value) {
            addCriterion("seq >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("seq >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(BigDecimal value) {
            addCriterion("seq <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(BigDecimal value) {
            addCriterion("seq <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<BigDecimal> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<BigDecimal> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andEvalscoreIsNull() {
            addCriterion("evalscore is null");
            return (Criteria) this;
        }

        public Criteria andEvalscoreIsNotNull() {
            addCriterion("evalscore is not null");
            return (Criteria) this;
        }

        public Criteria andEvalscoreEqualTo(String value) {
            addCriterion("evalscore =", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreNotEqualTo(String value) {
            addCriterion("evalscore <>", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreGreaterThan(String value) {
            addCriterion("evalscore >", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreGreaterThanOrEqualTo(String value) {
            addCriterion("evalscore >=", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreLessThan(String value) {
            addCriterion("evalscore <", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreLessThanOrEqualTo(String value) {
            addCriterion("evalscore <=", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreLike(String value) {
            addCriterion("evalscore like", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreNotLike(String value) {
            addCriterion("evalscore not like", value, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreIn(List<String> values) {
            addCriterion("evalscore in", values, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreNotIn(List<String> values) {
            addCriterion("evalscore not in", values, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreBetween(String value1, String value2) {
            addCriterion("evalscore between", value1, value2, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvalscoreNotBetween(String value1, String value2) {
            addCriterion("evalscore not between", value1, value2, "evalscore");
            return (Criteria) this;
        }

        public Criteria andEvaltimeIsNull() {
            addCriterion("evaltime is null");
            return (Criteria) this;
        }

        public Criteria andEvaltimeIsNotNull() {
            addCriterion("evaltime is not null");
            return (Criteria) this;
        }

        public Criteria andEvaltimeEqualTo(String value) {
            addCriterion("evaltime =", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeNotEqualTo(String value) {
            addCriterion("evaltime <>", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeGreaterThan(String value) {
            addCriterion("evaltime >", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeGreaterThanOrEqualTo(String value) {
            addCriterion("evaltime >=", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeLessThan(String value) {
            addCriterion("evaltime <", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeLessThanOrEqualTo(String value) {
            addCriterion("evaltime <=", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeLike(String value) {
            addCriterion("evaltime like", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeNotLike(String value) {
            addCriterion("evaltime not like", value, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeIn(List<String> values) {
            addCriterion("evaltime in", values, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeNotIn(List<String> values) {
            addCriterion("evaltime not in", values, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeBetween(String value1, String value2) {
            addCriterion("evaltime between", value1, value2, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaltimeNotBetween(String value1, String value2) {
            addCriterion("evaltime not between", value1, value2, "evaltime");
            return (Criteria) this;
        }

        public Criteria andEvaldeptIsNull() {
            addCriterion("evaldept is null");
            return (Criteria) this;
        }

        public Criteria andEvaldeptIsNotNull() {
            addCriterion("evaldept is not null");
            return (Criteria) this;
        }

        public Criteria andEvaldeptEqualTo(String value) {
            addCriterion("evaldept =", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptNotEqualTo(String value) {
            addCriterion("evaldept <>", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptGreaterThan(String value) {
            addCriterion("evaldept >", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptGreaterThanOrEqualTo(String value) {
            addCriterion("evaldept >=", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptLessThan(String value) {
            addCriterion("evaldept <", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptLessThanOrEqualTo(String value) {
            addCriterion("evaldept <=", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptLike(String value) {
            addCriterion("evaldept like", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptNotLike(String value) {
            addCriterion("evaldept not like", value, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptIn(List<String> values) {
            addCriterion("evaldept in", values, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptNotIn(List<String> values) {
            addCriterion("evaldept not in", values, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptBetween(String value1, String value2) {
            addCriterion("evaldept between", value1, value2, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvaldeptNotBetween(String value1, String value2) {
            addCriterion("evaldept not between", value1, value2, "evaldept");
            return (Criteria) this;
        }

        public Criteria andEvalnameIsNull() {
            addCriterion("evalname is null");
            return (Criteria) this;
        }

        public Criteria andEvalnameIsNotNull() {
            addCriterion("evalname is not null");
            return (Criteria) this;
        }

        public Criteria andEvalnameEqualTo(String value) {
            addCriterion("evalname =", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameNotEqualTo(String value) {
            addCriterion("evalname <>", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameGreaterThan(String value) {
            addCriterion("evalname >", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameGreaterThanOrEqualTo(String value) {
            addCriterion("evalname >=", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameLessThan(String value) {
            addCriterion("evalname <", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameLessThanOrEqualTo(String value) {
            addCriterion("evalname <=", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameLike(String value) {
            addCriterion("evalname like", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameNotLike(String value) {
            addCriterion("evalname not like", value, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameIn(List<String> values) {
            addCriterion("evalname in", values, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameNotIn(List<String> values) {
            addCriterion("evalname not in", values, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameBetween(String value1, String value2) {
            addCriterion("evalname between", value1, value2, "evalname");
            return (Criteria) this;
        }

        public Criteria andEvalnameNotBetween(String value1, String value2) {
            addCriterion("evalname not between", value1, value2, "evalname");
            return (Criteria) this;
        }

        public Criteria andFjIsNull() {
            addCriterion("fj is null");
            return (Criteria) this;
        }

        public Criteria andFjIsNotNull() {
            addCriterion("fj is not null");
            return (Criteria) this;
        }

        public Criteria andFjEqualTo(String value) {
            addCriterion("fj =", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotEqualTo(String value) {
            addCriterion("fj <>", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjGreaterThan(String value) {
            addCriterion("fj >", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjGreaterThanOrEqualTo(String value) {
            addCriterion("fj >=", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjLessThan(String value) {
            addCriterion("fj <", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjLessThanOrEqualTo(String value) {
            addCriterion("fj <=", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjLike(String value) {
            addCriterion("fj like", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotLike(String value) {
            addCriterion("fj not like", value, "fj");
            return (Criteria) this;
        }

        public Criteria andFjIn(List<String> values) {
            addCriterion("fj in", values, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotIn(List<String> values) {
            addCriterion("fj not in", values, "fj");
            return (Criteria) this;
        }

        public Criteria andFjBetween(String value1, String value2) {
            addCriterion("fj between", value1, value2, "fj");
            return (Criteria) this;
        }

        public Criteria andFjNotBetween(String value1, String value2) {
            addCriterion("fj not between", value1, value2, "fj");
            return (Criteria) this;
        }

        public Criteria andEvalsIsNull() {
            addCriterion("evals is null");
            return (Criteria) this;
        }

        public Criteria andEvalsIsNotNull() {
            addCriterion("evals is not null");
            return (Criteria) this;
        }

        public Criteria andEvalsEqualTo(String value) {
            addCriterion("evals =", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsNotEqualTo(String value) {
            addCriterion("evals <>", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsGreaterThan(String value) {
            addCriterion("evals >", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsGreaterThanOrEqualTo(String value) {
            addCriterion("evals >=", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsLessThan(String value) {
            addCriterion("evals <", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsLessThanOrEqualTo(String value) {
            addCriterion("evals <=", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsLike(String value) {
            addCriterion("evals like", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsNotLike(String value) {
            addCriterion("evals not like", value, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsIn(List<String> values) {
            addCriterion("evals in", values, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsNotIn(List<String> values) {
            addCriterion("evals not in", values, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsBetween(String value1, String value2) {
            addCriterion("evals between", value1, value2, "evals");
            return (Criteria) this;
        }

        public Criteria andEvalsNotBetween(String value1, String value2) {
            addCriterion("evals not between", value1, value2, "evals");
            return (Criteria) this;
        }

        public Criteria andSheetidIsNull() {
            addCriterion("sheetid is null");
            return (Criteria) this;
        }

        public Criteria andSheetidIsNotNull() {
            addCriterion("sheetid is not null");
            return (Criteria) this;
        }

        public Criteria andSheetidEqualTo(BigDecimal value) {
            addCriterion("sheetid =", value, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidNotEqualTo(BigDecimal value) {
            addCriterion("sheetid <>", value, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidGreaterThan(BigDecimal value) {
            addCriterion("sheetid >", value, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sheetid >=", value, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidLessThan(BigDecimal value) {
            addCriterion("sheetid <", value, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sheetid <=", value, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidIn(List<BigDecimal> values) {
            addCriterion("sheetid in", values, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidNotIn(List<BigDecimal> values) {
            addCriterion("sheetid not in", values, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sheetid between", value1, value2, "sheetid");
            return (Criteria) this;
        }

        public Criteria andSheetidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sheetid not between", value1, value2, "sheetid");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdIsNull() {
            addCriterion("eval_type_id is null");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdIsNotNull() {
            addCriterion("eval_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdEqualTo(BigDecimal value) {
            addCriterion("eval_type_id =", value, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdNotEqualTo(BigDecimal value) {
            addCriterion("eval_type_id <>", value, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdGreaterThan(BigDecimal value) {
            addCriterion("eval_type_id >", value, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("eval_type_id >=", value, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdLessThan(BigDecimal value) {
            addCriterion("eval_type_id <", value, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("eval_type_id <=", value, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdIn(List<BigDecimal> values) {
            addCriterion("eval_type_id in", values, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdNotIn(List<BigDecimal> values) {
            addCriterion("eval_type_id not in", values, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("eval_type_id between", value1, value2, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalTypeIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("eval_type_id not between", value1, value2, "evalTypeId");
            return (Criteria) this;
        }

        public Criteria andEvalImperIsNull() {
            addCriterion("eval_imper is null");
            return (Criteria) this;
        }

        public Criteria andEvalImperIsNotNull() {
            addCriterion("eval_imper is not null");
            return (Criteria) this;
        }

        public Criteria andEvalImperEqualTo(String value) {
            addCriterion("eval_imper =", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperNotEqualTo(String value) {
            addCriterion("eval_imper <>", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperGreaterThan(String value) {
            addCriterion("eval_imper >", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperGreaterThanOrEqualTo(String value) {
            addCriterion("eval_imper >=", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperLessThan(String value) {
            addCriterion("eval_imper <", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperLessThanOrEqualTo(String value) {
            addCriterion("eval_imper <=", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperLike(String value) {
            addCriterion("eval_imper like", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperNotLike(String value) {
            addCriterion("eval_imper not like", value, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperIn(List<String> values) {
            addCriterion("eval_imper in", values, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperNotIn(List<String> values) {
            addCriterion("eval_imper not in", values, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperBetween(String value1, String value2) {
            addCriterion("eval_imper between", value1, value2, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvalImperNotBetween(String value1, String value2) {
            addCriterion("eval_imper not between", value1, value2, "evalImper");
            return (Criteria) this;
        }

        public Criteria andEvaltime4IsNull() {
            addCriterion("evaltime4 is null");
            return (Criteria) this;
        }

        public Criteria andEvaltime4IsNotNull() {
            addCriterion("evaltime4 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaltime4EqualTo(String value) {
            addCriterion("evaltime4 =", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4NotEqualTo(String value) {
            addCriterion("evaltime4 <>", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4GreaterThan(String value) {
            addCriterion("evaltime4 >", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4GreaterThanOrEqualTo(String value) {
            addCriterion("evaltime4 >=", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4LessThan(String value) {
            addCriterion("evaltime4 <", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4LessThanOrEqualTo(String value) {
            addCriterion("evaltime4 <=", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4Like(String value) {
            addCriterion("evaltime4 like", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4NotLike(String value) {
            addCriterion("evaltime4 not like", value, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4In(List<String> values) {
            addCriterion("evaltime4 in", values, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4NotIn(List<String> values) {
            addCriterion("evaltime4 not in", values, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4Between(String value1, String value2) {
            addCriterion("evaltime4 between", value1, value2, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andEvaltime4NotBetween(String value1, String value2) {
            addCriterion("evaltime4 not between", value1, value2, "evaltime4");
            return (Criteria) this;
        }

        public Criteria andScore4IsNull() {
            addCriterion("score4 is null");
            return (Criteria) this;
        }

        public Criteria andScore4IsNotNull() {
            addCriterion("score4 is not null");
            return (Criteria) this;
        }

        public Criteria andScore4EqualTo(String value) {
            addCriterion("score4 =", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4NotEqualTo(String value) {
            addCriterion("score4 <>", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4GreaterThan(String value) {
            addCriterion("score4 >", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4GreaterThanOrEqualTo(String value) {
            addCriterion("score4 >=", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4LessThan(String value) {
            addCriterion("score4 <", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4LessThanOrEqualTo(String value) {
            addCriterion("score4 <=", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4Like(String value) {
            addCriterion("score4 like", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4NotLike(String value) {
            addCriterion("score4 not like", value, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4In(List<String> values) {
            addCriterion("score4 in", values, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4NotIn(List<String> values) {
            addCriterion("score4 not in", values, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4Between(String value1, String value2) {
            addCriterion("score4 between", value1, value2, "score4");
            return (Criteria) this;
        }

        public Criteria andScore4NotBetween(String value1, String value2) {
            addCriterion("score4 not between", value1, value2, "score4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4IsNull() {
            addCriterion("evalscore4 is null");
            return (Criteria) this;
        }

        public Criteria andEvalscore4IsNotNull() {
            addCriterion("evalscore4 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalscore4EqualTo(String value) {
            addCriterion("evalscore4 =", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4NotEqualTo(String value) {
            addCriterion("evalscore4 <>", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4GreaterThan(String value) {
            addCriterion("evalscore4 >", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4GreaterThanOrEqualTo(String value) {
            addCriterion("evalscore4 >=", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4LessThan(String value) {
            addCriterion("evalscore4 <", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4LessThanOrEqualTo(String value) {
            addCriterion("evalscore4 <=", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4Like(String value) {
            addCriterion("evalscore4 like", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4NotLike(String value) {
            addCriterion("evalscore4 not like", value, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4In(List<String> values) {
            addCriterion("evalscore4 in", values, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4NotIn(List<String> values) {
            addCriterion("evalscore4 not in", values, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4Between(String value1, String value2) {
            addCriterion("evalscore4 between", value1, value2, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andEvalscore4NotBetween(String value1, String value2) {
            addCriterion("evalscore4 not between", value1, value2, "evalscore4");
            return (Criteria) this;
        }

        public Criteria andScore3IsNull() {
            addCriterion("score3 is null");
            return (Criteria) this;
        }

        public Criteria andScore3IsNotNull() {
            addCriterion("score3 is not null");
            return (Criteria) this;
        }

        public Criteria andScore3EqualTo(String value) {
            addCriterion("score3 =", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3NotEqualTo(String value) {
            addCriterion("score3 <>", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3GreaterThan(String value) {
            addCriterion("score3 >", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3GreaterThanOrEqualTo(String value) {
            addCriterion("score3 >=", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3LessThan(String value) {
            addCriterion("score3 <", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3LessThanOrEqualTo(String value) {
            addCriterion("score3 <=", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3Like(String value) {
            addCriterion("score3 like", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3NotLike(String value) {
            addCriterion("score3 not like", value, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3In(List<String> values) {
            addCriterion("score3 in", values, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3NotIn(List<String> values) {
            addCriterion("score3 not in", values, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3Between(String value1, String value2) {
            addCriterion("score3 between", value1, value2, "score3");
            return (Criteria) this;
        }

        public Criteria andScore3NotBetween(String value1, String value2) {
            addCriterion("score3 not between", value1, value2, "score3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3IsNull() {
            addCriterion("evalscore3 is null");
            return (Criteria) this;
        }

        public Criteria andEvalscore3IsNotNull() {
            addCriterion("evalscore3 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalscore3EqualTo(String value) {
            addCriterion("evalscore3 =", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3NotEqualTo(String value) {
            addCriterion("evalscore3 <>", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3GreaterThan(String value) {
            addCriterion("evalscore3 >", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3GreaterThanOrEqualTo(String value) {
            addCriterion("evalscore3 >=", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3LessThan(String value) {
            addCriterion("evalscore3 <", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3LessThanOrEqualTo(String value) {
            addCriterion("evalscore3 <=", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3Like(String value) {
            addCriterion("evalscore3 like", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3NotLike(String value) {
            addCriterion("evalscore3 not like", value, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3In(List<String> values) {
            addCriterion("evalscore3 in", values, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3NotIn(List<String> values) {
            addCriterion("evalscore3 not in", values, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3Between(String value1, String value2) {
            addCriterion("evalscore3 between", value1, value2, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvalscore3NotBetween(String value1, String value2) {
            addCriterion("evalscore3 not between", value1, value2, "evalscore3");
            return (Criteria) this;
        }

        public Criteria andEvaldept2IsNull() {
            addCriterion("evaldept2 is null");
            return (Criteria) this;
        }

        public Criteria andEvaldept2IsNotNull() {
            addCriterion("evaldept2 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaldept2EqualTo(String value) {
            addCriterion("evaldept2 =", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2NotEqualTo(String value) {
            addCriterion("evaldept2 <>", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2GreaterThan(String value) {
            addCriterion("evaldept2 >", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2GreaterThanOrEqualTo(String value) {
            addCriterion("evaldept2 >=", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2LessThan(String value) {
            addCriterion("evaldept2 <", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2LessThanOrEqualTo(String value) {
            addCriterion("evaldept2 <=", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2Like(String value) {
            addCriterion("evaldept2 like", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2NotLike(String value) {
            addCriterion("evaldept2 not like", value, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2In(List<String> values) {
            addCriterion("evaldept2 in", values, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2NotIn(List<String> values) {
            addCriterion("evaldept2 not in", values, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2Between(String value1, String value2) {
            addCriterion("evaldept2 between", value1, value2, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvaldept2NotBetween(String value1, String value2) {
            addCriterion("evaldept2 not between", value1, value2, "evaldept2");
            return (Criteria) this;
        }

        public Criteria andEvalname2IsNull() {
            addCriterion("evalname2 is null");
            return (Criteria) this;
        }

        public Criteria andEvalname2IsNotNull() {
            addCriterion("evalname2 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalname2EqualTo(String value) {
            addCriterion("evalname2 =", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2NotEqualTo(String value) {
            addCriterion("evalname2 <>", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2GreaterThan(String value) {
            addCriterion("evalname2 >", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2GreaterThanOrEqualTo(String value) {
            addCriterion("evalname2 >=", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2LessThan(String value) {
            addCriterion("evalname2 <", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2LessThanOrEqualTo(String value) {
            addCriterion("evalname2 <=", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2Like(String value) {
            addCriterion("evalname2 like", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2NotLike(String value) {
            addCriterion("evalname2 not like", value, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2In(List<String> values) {
            addCriterion("evalname2 in", values, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2NotIn(List<String> values) {
            addCriterion("evalname2 not in", values, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2Between(String value1, String value2) {
            addCriterion("evalname2 between", value1, value2, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvalname2NotBetween(String value1, String value2) {
            addCriterion("evalname2 not between", value1, value2, "evalname2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2IsNull() {
            addCriterion("evaltime2 is null");
            return (Criteria) this;
        }

        public Criteria andEvaltime2IsNotNull() {
            addCriterion("evaltime2 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaltime2EqualTo(String value) {
            addCriterion("evaltime2 =", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2NotEqualTo(String value) {
            addCriterion("evaltime2 <>", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2GreaterThan(String value) {
            addCriterion("evaltime2 >", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2GreaterThanOrEqualTo(String value) {
            addCriterion("evaltime2 >=", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2LessThan(String value) {
            addCriterion("evaltime2 <", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2LessThanOrEqualTo(String value) {
            addCriterion("evaltime2 <=", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2Like(String value) {
            addCriterion("evaltime2 like", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2NotLike(String value) {
            addCriterion("evaltime2 not like", value, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2In(List<String> values) {
            addCriterion("evaltime2 in", values, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2NotIn(List<String> values) {
            addCriterion("evaltime2 not in", values, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2Between(String value1, String value2) {
            addCriterion("evaltime2 between", value1, value2, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andEvaltime2NotBetween(String value1, String value2) {
            addCriterion("evaltime2 not between", value1, value2, "evaltime2");
            return (Criteria) this;
        }

        public Criteria andScore2IsNull() {
            addCriterion("score2 is null");
            return (Criteria) this;
        }

        public Criteria andScore2IsNotNull() {
            addCriterion("score2 is not null");
            return (Criteria) this;
        }

        public Criteria andScore2EqualTo(String value) {
            addCriterion("score2 =", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2NotEqualTo(String value) {
            addCriterion("score2 <>", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2GreaterThan(String value) {
            addCriterion("score2 >", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2GreaterThanOrEqualTo(String value) {
            addCriterion("score2 >=", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2LessThan(String value) {
            addCriterion("score2 <", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2LessThanOrEqualTo(String value) {
            addCriterion("score2 <=", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2Like(String value) {
            addCriterion("score2 like", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2NotLike(String value) {
            addCriterion("score2 not like", value, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2In(List<String> values) {
            addCriterion("score2 in", values, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2NotIn(List<String> values) {
            addCriterion("score2 not in", values, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2Between(String value1, String value2) {
            addCriterion("score2 between", value1, value2, "score2");
            return (Criteria) this;
        }

        public Criteria andScore2NotBetween(String value1, String value2) {
            addCriterion("score2 not between", value1, value2, "score2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2IsNull() {
            addCriterion("evalscore2 is null");
            return (Criteria) this;
        }

        public Criteria andEvalscore2IsNotNull() {
            addCriterion("evalscore2 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalscore2EqualTo(String value) {
            addCriterion("evalscore2 =", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2NotEqualTo(String value) {
            addCriterion("evalscore2 <>", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2GreaterThan(String value) {
            addCriterion("evalscore2 >", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2GreaterThanOrEqualTo(String value) {
            addCriterion("evalscore2 >=", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2LessThan(String value) {
            addCriterion("evalscore2 <", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2LessThanOrEqualTo(String value) {
            addCriterion("evalscore2 <=", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2Like(String value) {
            addCriterion("evalscore2 like", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2NotLike(String value) {
            addCriterion("evalscore2 not like", value, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2In(List<String> values) {
            addCriterion("evalscore2 in", values, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2NotIn(List<String> values) {
            addCriterion("evalscore2 not in", values, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2Between(String value1, String value2) {
            addCriterion("evalscore2 between", value1, value2, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalscore2NotBetween(String value1, String value2) {
            addCriterion("evalscore2 not between", value1, value2, "evalscore2");
            return (Criteria) this;
        }

        public Criteria andEvalname1IsNull() {
            addCriterion("evalname1 is null");
            return (Criteria) this;
        }

        public Criteria andEvalname1IsNotNull() {
            addCriterion("evalname1 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalname1EqualTo(String value) {
            addCriterion("evalname1 =", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1NotEqualTo(String value) {
            addCriterion("evalname1 <>", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1GreaterThan(String value) {
            addCriterion("evalname1 >", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1GreaterThanOrEqualTo(String value) {
            addCriterion("evalname1 >=", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1LessThan(String value) {
            addCriterion("evalname1 <", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1LessThanOrEqualTo(String value) {
            addCriterion("evalname1 <=", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1Like(String value) {
            addCriterion("evalname1 like", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1NotLike(String value) {
            addCriterion("evalname1 not like", value, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1In(List<String> values) {
            addCriterion("evalname1 in", values, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1NotIn(List<String> values) {
            addCriterion("evalname1 not in", values, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1Between(String value1, String value2) {
            addCriterion("evalname1 between", value1, value2, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvalname1NotBetween(String value1, String value2) {
            addCriterion("evalname1 not between", value1, value2, "evalname1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1IsNull() {
            addCriterion("evaltime1 is null");
            return (Criteria) this;
        }

        public Criteria andEvaltime1IsNotNull() {
            addCriterion("evaltime1 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaltime1EqualTo(String value) {
            addCriterion("evaltime1 =", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1NotEqualTo(String value) {
            addCriterion("evaltime1 <>", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1GreaterThan(String value) {
            addCriterion("evaltime1 >", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1GreaterThanOrEqualTo(String value) {
            addCriterion("evaltime1 >=", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1LessThan(String value) {
            addCriterion("evaltime1 <", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1LessThanOrEqualTo(String value) {
            addCriterion("evaltime1 <=", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1Like(String value) {
            addCriterion("evaltime1 like", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1NotLike(String value) {
            addCriterion("evaltime1 not like", value, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1In(List<String> values) {
            addCriterion("evaltime1 in", values, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1NotIn(List<String> values) {
            addCriterion("evaltime1 not in", values, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1Between(String value1, String value2) {
            addCriterion("evaltime1 between", value1, value2, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvaltime1NotBetween(String value1, String value2) {
            addCriterion("evaltime1 not between", value1, value2, "evaltime1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1IsNull() {
            addCriterion("evalscore1 is null");
            return (Criteria) this;
        }

        public Criteria andEvalscore1IsNotNull() {
            addCriterion("evalscore1 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalscore1EqualTo(String value) {
            addCriterion("evalscore1 =", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1NotEqualTo(String value) {
            addCriterion("evalscore1 <>", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1GreaterThan(String value) {
            addCriterion("evalscore1 >", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1GreaterThanOrEqualTo(String value) {
            addCriterion("evalscore1 >=", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1LessThan(String value) {
            addCriterion("evalscore1 <", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1LessThanOrEqualTo(String value) {
            addCriterion("evalscore1 <=", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1Like(String value) {
            addCriterion("evalscore1 like", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1NotLike(String value) {
            addCriterion("evalscore1 not like", value, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1In(List<String> values) {
            addCriterion("evalscore1 in", values, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1NotIn(List<String> values) {
            addCriterion("evalscore1 not in", values, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1Between(String value1, String value2) {
            addCriterion("evalscore1 between", value1, value2, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andEvalscore1NotBetween(String value1, String value2) {
            addCriterion("evalscore1 not between", value1, value2, "evalscore1");
            return (Criteria) this;
        }

        public Criteria andScore1IsNull() {
            addCriterion("score1 is null");
            return (Criteria) this;
        }

        public Criteria andScore1IsNotNull() {
            addCriterion("score1 is not null");
            return (Criteria) this;
        }

        public Criteria andScore1EqualTo(String value) {
            addCriterion("score1 =", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1NotEqualTo(String value) {
            addCriterion("score1 <>", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1GreaterThan(String value) {
            addCriterion("score1 >", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1GreaterThanOrEqualTo(String value) {
            addCriterion("score1 >=", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1LessThan(String value) {
            addCriterion("score1 <", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1LessThanOrEqualTo(String value) {
            addCriterion("score1 <=", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1Like(String value) {
            addCriterion("score1 like", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1NotLike(String value) {
            addCriterion("score1 not like", value, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1In(List<String> values) {
            addCriterion("score1 in", values, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1NotIn(List<String> values) {
            addCriterion("score1 not in", values, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1Between(String value1, String value2) {
            addCriterion("score1 between", value1, value2, "score1");
            return (Criteria) this;
        }

        public Criteria andScore1NotBetween(String value1, String value2) {
            addCriterion("score1 not between", value1, value2, "score1");
            return (Criteria) this;
        }

        public Criteria andEvaldept3IsNull() {
            addCriterion("evaldept3 is null");
            return (Criteria) this;
        }

        public Criteria andEvaldept3IsNotNull() {
            addCriterion("evaldept3 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaldept3EqualTo(String value) {
            addCriterion("evaldept3 =", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3NotEqualTo(String value) {
            addCriterion("evaldept3 <>", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3GreaterThan(String value) {
            addCriterion("evaldept3 >", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3GreaterThanOrEqualTo(String value) {
            addCriterion("evaldept3 >=", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3LessThan(String value) {
            addCriterion("evaldept3 <", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3LessThanOrEqualTo(String value) {
            addCriterion("evaldept3 <=", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3Like(String value) {
            addCriterion("evaldept3 like", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3NotLike(String value) {
            addCriterion("evaldept3 not like", value, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3In(List<String> values) {
            addCriterion("evaldept3 in", values, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3NotIn(List<String> values) {
            addCriterion("evaldept3 not in", values, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3Between(String value1, String value2) {
            addCriterion("evaldept3 between", value1, value2, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept3NotBetween(String value1, String value2) {
            addCriterion("evaldept3 not between", value1, value2, "evaldept3");
            return (Criteria) this;
        }

        public Criteria andEvaldept4IsNull() {
            addCriterion("evaldept4 is null");
            return (Criteria) this;
        }

        public Criteria andEvaldept4IsNotNull() {
            addCriterion("evaldept4 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaldept4EqualTo(String value) {
            addCriterion("evaldept4 =", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4NotEqualTo(String value) {
            addCriterion("evaldept4 <>", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4GreaterThan(String value) {
            addCriterion("evaldept4 >", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4GreaterThanOrEqualTo(String value) {
            addCriterion("evaldept4 >=", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4LessThan(String value) {
            addCriterion("evaldept4 <", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4LessThanOrEqualTo(String value) {
            addCriterion("evaldept4 <=", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4Like(String value) {
            addCriterion("evaldept4 like", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4NotLike(String value) {
            addCriterion("evaldept4 not like", value, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4In(List<String> values) {
            addCriterion("evaldept4 in", values, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4NotIn(List<String> values) {
            addCriterion("evaldept4 not in", values, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4Between(String value1, String value2) {
            addCriterion("evaldept4 between", value1, value2, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaldept4NotBetween(String value1, String value2) {
            addCriterion("evaldept4 not between", value1, value2, "evaldept4");
            return (Criteria) this;
        }

        public Criteria andEvaltime3IsNull() {
            addCriterion("evaltime3 is null");
            return (Criteria) this;
        }

        public Criteria andEvaltime3IsNotNull() {
            addCriterion("evaltime3 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaltime3EqualTo(String value) {
            addCriterion("evaltime3 =", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3NotEqualTo(String value) {
            addCriterion("evaltime3 <>", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3GreaterThan(String value) {
            addCriterion("evaltime3 >", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3GreaterThanOrEqualTo(String value) {
            addCriterion("evaltime3 >=", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3LessThan(String value) {
            addCriterion("evaltime3 <", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3LessThanOrEqualTo(String value) {
            addCriterion("evaltime3 <=", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3Like(String value) {
            addCriterion("evaltime3 like", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3NotLike(String value) {
            addCriterion("evaltime3 not like", value, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3In(List<String> values) {
            addCriterion("evaltime3 in", values, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3NotIn(List<String> values) {
            addCriterion("evaltime3 not in", values, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3Between(String value1, String value2) {
            addCriterion("evaltime3 between", value1, value2, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvaltime3NotBetween(String value1, String value2) {
            addCriterion("evaltime3 not between", value1, value2, "evaltime3");
            return (Criteria) this;
        }

        public Criteria andEvalname3IsNull() {
            addCriterion("evalname3 is null");
            return (Criteria) this;
        }

        public Criteria andEvalname3IsNotNull() {
            addCriterion("evalname3 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalname3EqualTo(String value) {
            addCriterion("evalname3 =", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3NotEqualTo(String value) {
            addCriterion("evalname3 <>", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3GreaterThan(String value) {
            addCriterion("evalname3 >", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3GreaterThanOrEqualTo(String value) {
            addCriterion("evalname3 >=", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3LessThan(String value) {
            addCriterion("evalname3 <", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3LessThanOrEqualTo(String value) {
            addCriterion("evalname3 <=", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3Like(String value) {
            addCriterion("evalname3 like", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3NotLike(String value) {
            addCriterion("evalname3 not like", value, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3In(List<String> values) {
            addCriterion("evalname3 in", values, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3NotIn(List<String> values) {
            addCriterion("evalname3 not in", values, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3Between(String value1, String value2) {
            addCriterion("evalname3 between", value1, value2, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname3NotBetween(String value1, String value2) {
            addCriterion("evalname3 not between", value1, value2, "evalname3");
            return (Criteria) this;
        }

        public Criteria andEvalname4IsNull() {
            addCriterion("evalname4 is null");
            return (Criteria) this;
        }

        public Criteria andEvalname4IsNotNull() {
            addCriterion("evalname4 is not null");
            return (Criteria) this;
        }

        public Criteria andEvalname4EqualTo(String value) {
            addCriterion("evalname4 =", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4NotEqualTo(String value) {
            addCriterion("evalname4 <>", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4GreaterThan(String value) {
            addCriterion("evalname4 >", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4GreaterThanOrEqualTo(String value) {
            addCriterion("evalname4 >=", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4LessThan(String value) {
            addCriterion("evalname4 <", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4LessThanOrEqualTo(String value) {
            addCriterion("evalname4 <=", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4Like(String value) {
            addCriterion("evalname4 like", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4NotLike(String value) {
            addCriterion("evalname4 not like", value, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4In(List<String> values) {
            addCriterion("evalname4 in", values, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4NotIn(List<String> values) {
            addCriterion("evalname4 not in", values, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4Between(String value1, String value2) {
            addCriterion("evalname4 between", value1, value2, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvalname4NotBetween(String value1, String value2) {
            addCriterion("evalname4 not between", value1, value2, "evalname4");
            return (Criteria) this;
        }

        public Criteria andEvaldept1IsNull() {
            addCriterion("evaldept1 is null");
            return (Criteria) this;
        }

        public Criteria andEvaldept1IsNotNull() {
            addCriterion("evaldept1 is not null");
            return (Criteria) this;
        }

        public Criteria andEvaldept1EqualTo(String value) {
            addCriterion("evaldept1 =", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1NotEqualTo(String value) {
            addCriterion("evaldept1 <>", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1GreaterThan(String value) {
            addCriterion("evaldept1 >", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1GreaterThanOrEqualTo(String value) {
            addCriterion("evaldept1 >=", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1LessThan(String value) {
            addCriterion("evaldept1 <", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1LessThanOrEqualTo(String value) {
            addCriterion("evaldept1 <=", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1Like(String value) {
            addCriterion("evaldept1 like", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1NotLike(String value) {
            addCriterion("evaldept1 not like", value, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1In(List<String> values) {
            addCriterion("evaldept1 in", values, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1NotIn(List<String> values) {
            addCriterion("evaldept1 not in", values, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1Between(String value1, String value2) {
            addCriterion("evaldept1 between", value1, value2, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andEvaldept1NotBetween(String value1, String value2) {
            addCriterion("evaldept1 not between", value1, value2, "evaldept1");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 27 16:15:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}