package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class EvalManagementScoreWithBLOBs extends EvalManagementScore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.name
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldescr
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldescr4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldescr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldescr3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldescr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldescr2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldescr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldescr1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldescr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.name
     *
     * @return the value of fx_eval_management_score.name
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.name
     *
     * @param name the value for fx_eval_management_score.name
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldescr
     *
     * @return the value of fx_eval_management_score.evaldescr
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldescr() {
        return evaldescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldescr
     *
     * @param evaldescr the value for fx_eval_management_score.evaldescr
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldescr(String evaldescr) {
        this.evaldescr = evaldescr == null ? null : evaldescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldescr4
     *
     * @return the value of fx_eval_management_score.evaldescr4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldescr4() {
        return evaldescr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldescr4
     *
     * @param evaldescr4 the value for fx_eval_management_score.evaldescr4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldescr4(String evaldescr4) {
        this.evaldescr4 = evaldescr4 == null ? null : evaldescr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldescr3
     *
     * @return the value of fx_eval_management_score.evaldescr3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldescr3() {
        return evaldescr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldescr3
     *
     * @param evaldescr3 the value for fx_eval_management_score.evaldescr3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldescr3(String evaldescr3) {
        this.evaldescr3 = evaldescr3 == null ? null : evaldescr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldescr2
     *
     * @return the value of fx_eval_management_score.evaldescr2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldescr2() {
        return evaldescr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldescr2
     *
     * @param evaldescr2 the value for fx_eval_management_score.evaldescr2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldescr2(String evaldescr2) {
        this.evaldescr2 = evaldescr2 == null ? null : evaldescr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldescr1
     *
     * @return the value of fx_eval_management_score.evaldescr1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldescr1() {
        return evaldescr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldescr1
     *
     * @param evaldescr1 the value for fx_eval_management_score.evaldescr1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldescr1(String evaldescr1) {
        this.evaldescr1 = evaldescr1 == null ? null : evaldescr1.trim();
    }
}