package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;

public class EvalManagementScore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.id
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.code
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.managementid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private BigDecimal managementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.catalogid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private BigDecimal catalogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.standscore
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String standscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.seq
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private BigDecimal seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalscore
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaltime
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldept
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalname
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.fj
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String fj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evals
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.sheetid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private BigDecimal sheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.eval_type_id
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private BigDecimal evalTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.eval_imper
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalImper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaltime4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaltime4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.score4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String score4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalscore4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalscore4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.score3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String score3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalscore3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalscore3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldept2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldept2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalname2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaltime2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaltime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.score2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String score2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalscore2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalscore2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalname1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalname1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaltime1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaltime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalscore1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalscore1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.score1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String score1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldept3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldept3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldept4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldept4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaltime3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaltime3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalname3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalname3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evalname4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evalname4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.evaldept1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String evaldept1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fx_eval_management_score.state
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fx_eval_management_score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.id
     *
     * @return the value of fx_eval_management_score.id
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.id
     *
     * @param id the value for fx_eval_management_score.id
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.code
     *
     * @return the value of fx_eval_management_score.code
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.code
     *
     * @param code the value for fx_eval_management_score.code
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.score
     *
     * @return the value of fx_eval_management_score.score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.score
     *
     * @param score the value for fx_eval_management_score.score
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.managementid
     *
     * @return the value of fx_eval_management_score.managementid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public BigDecimal getManagementid() {
        return managementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.managementid
     *
     * @param managementid the value for fx_eval_management_score.managementid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setManagementid(BigDecimal managementid) {
        this.managementid = managementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.catalogid
     *
     * @return the value of fx_eval_management_score.catalogid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public BigDecimal getCatalogid() {
        return catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.catalogid
     *
     * @param catalogid the value for fx_eval_management_score.catalogid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setCatalogid(BigDecimal catalogid) {
        this.catalogid = catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.standscore
     *
     * @return the value of fx_eval_management_score.standscore
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getStandscore() {
        return standscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.standscore
     *
     * @param standscore the value for fx_eval_management_score.standscore
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setStandscore(String standscore) {
        this.standscore = standscore == null ? null : standscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.seq
     *
     * @return the value of fx_eval_management_score.seq
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public BigDecimal getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.seq
     *
     * @param seq the value for fx_eval_management_score.seq
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalscore
     *
     * @return the value of fx_eval_management_score.evalscore
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalscore() {
        return evalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalscore
     *
     * @param evalscore the value for fx_eval_management_score.evalscore
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalscore(String evalscore) {
        this.evalscore = evalscore == null ? null : evalscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaltime
     *
     * @return the value of fx_eval_management_score.evaltime
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaltime() {
        return evaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaltime
     *
     * @param evaltime the value for fx_eval_management_score.evaltime
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaltime(String evaltime) {
        this.evaltime = evaltime == null ? null : evaltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldept
     *
     * @return the value of fx_eval_management_score.evaldept
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldept() {
        return evaldept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldept
     *
     * @param evaldept the value for fx_eval_management_score.evaldept
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldept(String evaldept) {
        this.evaldept = evaldept == null ? null : evaldept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalname
     *
     * @return the value of fx_eval_management_score.evalname
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalname() {
        return evalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalname
     *
     * @param evalname the value for fx_eval_management_score.evalname
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalname(String evalname) {
        this.evalname = evalname == null ? null : evalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.fj
     *
     * @return the value of fx_eval_management_score.fj
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getFj() {
        return fj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.fj
     *
     * @param fj the value for fx_eval_management_score.fj
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setFj(String fj) {
        this.fj = fj == null ? null : fj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evals
     *
     * @return the value of fx_eval_management_score.evals
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvals() {
        return evals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evals
     *
     * @param evals the value for fx_eval_management_score.evals
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvals(String evals) {
        this.evals = evals == null ? null : evals.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.sheetid
     *
     * @return the value of fx_eval_management_score.sheetid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public BigDecimal getSheetid() {
        return sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.sheetid
     *
     * @param sheetid the value for fx_eval_management_score.sheetid
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setSheetid(BigDecimal sheetid) {
        this.sheetid = sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.eval_type_id
     *
     * @return the value of fx_eval_management_score.eval_type_id
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public BigDecimal getEvalTypeId() {
        return evalTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.eval_type_id
     *
     * @param evalTypeId the value for fx_eval_management_score.eval_type_id
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalTypeId(BigDecimal evalTypeId) {
        this.evalTypeId = evalTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.eval_imper
     *
     * @return the value of fx_eval_management_score.eval_imper
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalImper() {
        return evalImper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.eval_imper
     *
     * @param evalImper the value for fx_eval_management_score.eval_imper
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalImper(String evalImper) {
        this.evalImper = evalImper == null ? null : evalImper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaltime4
     *
     * @return the value of fx_eval_management_score.evaltime4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaltime4() {
        return evaltime4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaltime4
     *
     * @param evaltime4 the value for fx_eval_management_score.evaltime4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaltime4(String evaltime4) {
        this.evaltime4 = evaltime4 == null ? null : evaltime4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.score4
     *
     * @return the value of fx_eval_management_score.score4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getScore4() {
        return score4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.score4
     *
     * @param score4 the value for fx_eval_management_score.score4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setScore4(String score4) {
        this.score4 = score4 == null ? null : score4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalscore4
     *
     * @return the value of fx_eval_management_score.evalscore4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalscore4() {
        return evalscore4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalscore4
     *
     * @param evalscore4 the value for fx_eval_management_score.evalscore4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalscore4(String evalscore4) {
        this.evalscore4 = evalscore4 == null ? null : evalscore4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.score3
     *
     * @return the value of fx_eval_management_score.score3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getScore3() {
        return score3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.score3
     *
     * @param score3 the value for fx_eval_management_score.score3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setScore3(String score3) {
        this.score3 = score3 == null ? null : score3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalscore3
     *
     * @return the value of fx_eval_management_score.evalscore3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalscore3() {
        return evalscore3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalscore3
     *
     * @param evalscore3 the value for fx_eval_management_score.evalscore3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalscore3(String evalscore3) {
        this.evalscore3 = evalscore3 == null ? null : evalscore3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldept2
     *
     * @return the value of fx_eval_management_score.evaldept2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldept2() {
        return evaldept2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldept2
     *
     * @param evaldept2 the value for fx_eval_management_score.evaldept2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldept2(String evaldept2) {
        this.evaldept2 = evaldept2 == null ? null : evaldept2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalname2
     *
     * @return the value of fx_eval_management_score.evalname2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalname2() {
        return evalname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalname2
     *
     * @param evalname2 the value for fx_eval_management_score.evalname2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalname2(String evalname2) {
        this.evalname2 = evalname2 == null ? null : evalname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaltime2
     *
     * @return the value of fx_eval_management_score.evaltime2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaltime2() {
        return evaltime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaltime2
     *
     * @param evaltime2 the value for fx_eval_management_score.evaltime2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaltime2(String evaltime2) {
        this.evaltime2 = evaltime2 == null ? null : evaltime2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.score2
     *
     * @return the value of fx_eval_management_score.score2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.score2
     *
     * @param score2 the value for fx_eval_management_score.score2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setScore2(String score2) {
        this.score2 = score2 == null ? null : score2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalscore2
     *
     * @return the value of fx_eval_management_score.evalscore2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalscore2() {
        return evalscore2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalscore2
     *
     * @param evalscore2 the value for fx_eval_management_score.evalscore2
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalscore2(String evalscore2) {
        this.evalscore2 = evalscore2 == null ? null : evalscore2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalname1
     *
     * @return the value of fx_eval_management_score.evalname1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalname1() {
        return evalname1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalname1
     *
     * @param evalname1 the value for fx_eval_management_score.evalname1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalname1(String evalname1) {
        this.evalname1 = evalname1 == null ? null : evalname1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaltime1
     *
     * @return the value of fx_eval_management_score.evaltime1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaltime1() {
        return evaltime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaltime1
     *
     * @param evaltime1 the value for fx_eval_management_score.evaltime1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaltime1(String evaltime1) {
        this.evaltime1 = evaltime1 == null ? null : evaltime1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalscore1
     *
     * @return the value of fx_eval_management_score.evalscore1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalscore1() {
        return evalscore1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalscore1
     *
     * @param evalscore1 the value for fx_eval_management_score.evalscore1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalscore1(String evalscore1) {
        this.evalscore1 = evalscore1 == null ? null : evalscore1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.score1
     *
     * @return the value of fx_eval_management_score.score1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.score1
     *
     * @param score1 the value for fx_eval_management_score.score1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setScore1(String score1) {
        this.score1 = score1 == null ? null : score1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldept3
     *
     * @return the value of fx_eval_management_score.evaldept3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldept3() {
        return evaldept3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldept3
     *
     * @param evaldept3 the value for fx_eval_management_score.evaldept3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldept3(String evaldept3) {
        this.evaldept3 = evaldept3 == null ? null : evaldept3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldept4
     *
     * @return the value of fx_eval_management_score.evaldept4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldept4() {
        return evaldept4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldept4
     *
     * @param evaldept4 the value for fx_eval_management_score.evaldept4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldept4(String evaldept4) {
        this.evaldept4 = evaldept4 == null ? null : evaldept4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaltime3
     *
     * @return the value of fx_eval_management_score.evaltime3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaltime3() {
        return evaltime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaltime3
     *
     * @param evaltime3 the value for fx_eval_management_score.evaltime3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaltime3(String evaltime3) {
        this.evaltime3 = evaltime3 == null ? null : evaltime3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalname3
     *
     * @return the value of fx_eval_management_score.evalname3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalname3() {
        return evalname3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalname3
     *
     * @param evalname3 the value for fx_eval_management_score.evalname3
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalname3(String evalname3) {
        this.evalname3 = evalname3 == null ? null : evalname3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evalname4
     *
     * @return the value of fx_eval_management_score.evalname4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvalname4() {
        return evalname4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evalname4
     *
     * @param evalname4 the value for fx_eval_management_score.evalname4
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvalname4(String evalname4) {
        this.evalname4 = evalname4 == null ? null : evalname4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.evaldept1
     *
     * @return the value of fx_eval_management_score.evaldept1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getEvaldept1() {
        return evaldept1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.evaldept1
     *
     * @param evaldept1 the value for fx_eval_management_score.evaldept1
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setEvaldept1(String evaldept1) {
        this.evaldept1 = evaldept1 == null ? null : evaldept1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fx_eval_management_score.state
     *
     * @return the value of fx_eval_management_score.state
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fx_eval_management_score.state
     *
     * @param state the value for fx_eval_management_score.state
     *
     * @mbg.generated Thu Sep 27 16:15:16 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}