package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class HtywOrgizationWithBLOBs extends HtywOrgization implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.breach
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String breach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.employees
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String employees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.area
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.setid
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String setid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.typeid
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.inquiry
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String inquiry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.xqscore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String xqscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.cjscore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String cjscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bFactoryType
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bfactorytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bStatus
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bIsFormal
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bisformal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.breach
     *
     * @return the value of htyw_orgization.breach
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getBreach() {
        return breach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.breach
     *
     * @param breach the value for htyw_orgization.breach
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setBreach(String breach) {
        this.breach = breach == null ? null : breach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.employees
     *
     * @return the value of htyw_orgization.employees
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getEmployees() {
        return employees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.employees
     *
     * @param employees the value for htyw_orgization.employees
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setEmployees(String employees) {
        this.employees = employees == null ? null : employees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.area
     *
     * @return the value of htyw_orgization.area
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.area
     *
     * @param area the value for htyw_orgization.area
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.setid
     *
     * @return the value of htyw_orgization.setid
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getSetid() {
        return setid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.setid
     *
     * @param setid the value for htyw_orgization.setid
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setSetid(String setid) {
        this.setid = setid == null ? null : setid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.typeid
     *
     * @return the value of htyw_orgization.typeid
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.typeid
     *
     * @param typeid the value for htyw_orgization.typeid
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.inquiry
     *
     * @return the value of htyw_orgization.inquiry
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getInquiry() {
        return inquiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.inquiry
     *
     * @param inquiry the value for htyw_orgization.inquiry
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setInquiry(String inquiry) {
        this.inquiry = inquiry == null ? null : inquiry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.xqscore
     *
     * @return the value of htyw_orgization.xqscore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getXqscore() {
        return xqscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.xqscore
     *
     * @param xqscore the value for htyw_orgization.xqscore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setXqscore(String xqscore) {
        this.xqscore = xqscore == null ? null : xqscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.cjscore
     *
     * @return the value of htyw_orgization.cjscore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCjscore() {
        return cjscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.cjscore
     *
     * @param cjscore the value for htyw_orgization.cjscore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCjscore(String cjscore) {
        this.cjscore = cjscore == null ? null : cjscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bFactoryType
     *
     * @return the value of htyw_orgization.b2bFactoryType
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bfactorytype() {
        return b2bfactorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bFactoryType
     *
     * @param b2bfactorytype the value for htyw_orgization.b2bFactoryType
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bfactorytype(String b2bfactorytype) {
        this.b2bfactorytype = b2bfactorytype == null ? null : b2bfactorytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bStatus
     *
     * @return the value of htyw_orgization.b2bStatus
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bstatus() {
        return b2bstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bStatus
     *
     * @param b2bstatus the value for htyw_orgization.b2bStatus
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bstatus(String b2bstatus) {
        this.b2bstatus = b2bstatus == null ? null : b2bstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bIsFormal
     *
     * @return the value of htyw_orgization.b2bIsFormal
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bisformal() {
        return b2bisformal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bIsFormal
     *
     * @param b2bisformal the value for htyw_orgization.b2bIsFormal
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bisformal(String b2bisformal) {
        this.b2bisformal = b2bisformal == null ? null : b2bisformal.trim();
    }
}