package com.casic.oarp.datavisual.po;

import java.io.Serializable;

public class HtywOrgization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.sysOrgInfoId
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String sysorginfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.email
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.name
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.industry
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.scale
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.address
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.postcode
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.connecter
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String connecter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.tel
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.fax
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.homephone
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String homephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.logo
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.industry2
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String industry2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.info
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.country
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.province
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.city
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.code
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.type
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.model
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.product
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.website
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.isPublic
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String ispublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.registertime
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.flaglogo
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String flaglogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.state
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.manageRange
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String managerange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.regProve
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String regprove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.sellArea
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String sellarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.brand
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.clients
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String clients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.turnover
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.exportFore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String exportfore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.importFore
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String importfore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.qualityControl
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String qualitycontrol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.regCapital
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String regcapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.regAdd
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String regadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.incorporator
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String incorporator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.openBank
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String openbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.openAccount
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String openaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.showimage
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String showimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.sellArea2
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String sellarea2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.createtime
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.recommendedent
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String recommendedent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.qrcode
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.orgtype
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String orgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.filePath
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.fileName
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.checkPersonAId
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String checkpersonaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.checkPersonAName
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String checkpersonaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.typename
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.managetype
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String managetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bFactoryInnerName
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bfactoryinnername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bFactorySuperior
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bfactorysuperior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bFactoryOpenBankAddress
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bfactoryopenbankaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bFactoryOpenAccountName
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bfactoryopenaccountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bFactoryProductionAddress
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bfactoryproductionaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bOrganizationCode
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2borganizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bOrganizationPath
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2borganizationpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bBusinessLicenseCode
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bbusinesslicensecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bBusinessLicensePath
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bbusinesslicensepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bNationalTaxCode
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bnationaltaxcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bNationalTaxPath
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bnationaltaxpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bUpdateDate
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bParentCode
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bparentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bParentName
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bparentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.b2bManagementLevel
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String b2bmanagementlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.businessType
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String businesstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.specialLine
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String specialline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column htyw_orgization.updatetime
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table htyw_orgization
     *
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.sysOrgInfoId
     *
     * @return the value of htyw_orgization.sysOrgInfoId
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getSysorginfoid() {
        return sysorginfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.sysOrgInfoId
     *
     * @param sysorginfoid the value for htyw_orgization.sysOrgInfoId
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setSysorginfoid(String sysorginfoid) {
        this.sysorginfoid = sysorginfoid == null ? null : sysorginfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.email
     *
     * @return the value of htyw_orgization.email
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.email
     *
     * @param email the value for htyw_orgization.email
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.name
     *
     * @return the value of htyw_orgization.name
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.name
     *
     * @param name the value for htyw_orgization.name
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.industry
     *
     * @return the value of htyw_orgization.industry
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.industry
     *
     * @param industry the value for htyw_orgization.industry
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.scale
     *
     * @return the value of htyw_orgization.scale
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.scale
     *
     * @param scale the value for htyw_orgization.scale
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.address
     *
     * @return the value of htyw_orgization.address
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.address
     *
     * @param address the value for htyw_orgization.address
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.postcode
     *
     * @return the value of htyw_orgization.postcode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.postcode
     *
     * @param postcode the value for htyw_orgization.postcode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.connecter
     *
     * @return the value of htyw_orgization.connecter
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getConnecter() {
        return connecter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.connecter
     *
     * @param connecter the value for htyw_orgization.connecter
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setConnecter(String connecter) {
        this.connecter = connecter == null ? null : connecter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.tel
     *
     * @return the value of htyw_orgization.tel
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.tel
     *
     * @param tel the value for htyw_orgization.tel
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.fax
     *
     * @return the value of htyw_orgization.fax
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.fax
     *
     * @param fax the value for htyw_orgization.fax
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.homephone
     *
     * @return the value of htyw_orgization.homephone
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getHomephone() {
        return homephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.homephone
     *
     * @param homephone the value for htyw_orgization.homephone
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setHomephone(String homephone) {
        this.homephone = homephone == null ? null : homephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.logo
     *
     * @return the value of htyw_orgization.logo
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.logo
     *
     * @param logo the value for htyw_orgization.logo
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.industry2
     *
     * @return the value of htyw_orgization.industry2
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getIndustry2() {
        return industry2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.industry2
     *
     * @param industry2 the value for htyw_orgization.industry2
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setIndustry2(String industry2) {
        this.industry2 = industry2 == null ? null : industry2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.info
     *
     * @return the value of htyw_orgization.info
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.info
     *
     * @param info the value for htyw_orgization.info
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.country
     *
     * @return the value of htyw_orgization.country
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.country
     *
     * @param country the value for htyw_orgization.country
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.province
     *
     * @return the value of htyw_orgization.province
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.province
     *
     * @param province the value for htyw_orgization.province
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.city
     *
     * @return the value of htyw_orgization.city
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.city
     *
     * @param city the value for htyw_orgization.city
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.code
     *
     * @return the value of htyw_orgization.code
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.code
     *
     * @param code the value for htyw_orgization.code
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.type
     *
     * @return the value of htyw_orgization.type
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.type
     *
     * @param type the value for htyw_orgization.type
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.model
     *
     * @return the value of htyw_orgization.model
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.model
     *
     * @param model the value for htyw_orgization.model
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.product
     *
     * @return the value of htyw_orgization.product
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.product
     *
     * @param product the value for htyw_orgization.product
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.website
     *
     * @return the value of htyw_orgization.website
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.website
     *
     * @param website the value for htyw_orgization.website
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.isPublic
     *
     * @return the value of htyw_orgization.isPublic
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getIspublic() {
        return ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.isPublic
     *
     * @param ispublic the value for htyw_orgization.isPublic
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setIspublic(String ispublic) {
        this.ispublic = ispublic == null ? null : ispublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.registertime
     *
     * @return the value of htyw_orgization.registertime
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.registertime
     *
     * @param registertime the value for htyw_orgization.registertime
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime == null ? null : registertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.flaglogo
     *
     * @return the value of htyw_orgization.flaglogo
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getFlaglogo() {
        return flaglogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.flaglogo
     *
     * @param flaglogo the value for htyw_orgization.flaglogo
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setFlaglogo(String flaglogo) {
        this.flaglogo = flaglogo == null ? null : flaglogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.state
     *
     * @return the value of htyw_orgization.state
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.state
     *
     * @param state the value for htyw_orgization.state
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.manageRange
     *
     * @return the value of htyw_orgization.manageRange
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getManagerange() {
        return managerange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.manageRange
     *
     * @param managerange the value for htyw_orgization.manageRange
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setManagerange(String managerange) {
        this.managerange = managerange == null ? null : managerange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.regProve
     *
     * @return the value of htyw_orgization.regProve
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getRegprove() {
        return regprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.regProve
     *
     * @param regprove the value for htyw_orgization.regProve
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setRegprove(String regprove) {
        this.regprove = regprove == null ? null : regprove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.sellArea
     *
     * @return the value of htyw_orgization.sellArea
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getSellarea() {
        return sellarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.sellArea
     *
     * @param sellarea the value for htyw_orgization.sellArea
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setSellarea(String sellarea) {
        this.sellarea = sellarea == null ? null : sellarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.brand
     *
     * @return the value of htyw_orgization.brand
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.brand
     *
     * @param brand the value for htyw_orgization.brand
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.clients
     *
     * @return the value of htyw_orgization.clients
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getClients() {
        return clients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.clients
     *
     * @param clients the value for htyw_orgization.clients
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setClients(String clients) {
        this.clients = clients == null ? null : clients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.turnover
     *
     * @return the value of htyw_orgization.turnover
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.turnover
     *
     * @param turnover the value for htyw_orgization.turnover
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setTurnover(String turnover) {
        this.turnover = turnover == null ? null : turnover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.exportFore
     *
     * @return the value of htyw_orgization.exportFore
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getExportfore() {
        return exportfore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.exportFore
     *
     * @param exportfore the value for htyw_orgization.exportFore
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setExportfore(String exportfore) {
        this.exportfore = exportfore == null ? null : exportfore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.importFore
     *
     * @return the value of htyw_orgization.importFore
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getImportfore() {
        return importfore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.importFore
     *
     * @param importfore the value for htyw_orgization.importFore
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setImportfore(String importfore) {
        this.importfore = importfore == null ? null : importfore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.qualityControl
     *
     * @return the value of htyw_orgization.qualityControl
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getQualitycontrol() {
        return qualitycontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.qualityControl
     *
     * @param qualitycontrol the value for htyw_orgization.qualityControl
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setQualitycontrol(String qualitycontrol) {
        this.qualitycontrol = qualitycontrol == null ? null : qualitycontrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.regCapital
     *
     * @return the value of htyw_orgization.regCapital
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getRegcapital() {
        return regcapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.regCapital
     *
     * @param regcapital the value for htyw_orgization.regCapital
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setRegcapital(String regcapital) {
        this.regcapital = regcapital == null ? null : regcapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.regAdd
     *
     * @return the value of htyw_orgization.regAdd
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getRegadd() {
        return regadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.regAdd
     *
     * @param regadd the value for htyw_orgization.regAdd
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setRegadd(String regadd) {
        this.regadd = regadd == null ? null : regadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.incorporator
     *
     * @return the value of htyw_orgization.incorporator
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getIncorporator() {
        return incorporator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.incorporator
     *
     * @param incorporator the value for htyw_orgization.incorporator
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setIncorporator(String incorporator) {
        this.incorporator = incorporator == null ? null : incorporator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.openBank
     *
     * @return the value of htyw_orgization.openBank
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getOpenbank() {
        return openbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.openBank
     *
     * @param openbank the value for htyw_orgization.openBank
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setOpenbank(String openbank) {
        this.openbank = openbank == null ? null : openbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.openAccount
     *
     * @return the value of htyw_orgization.openAccount
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getOpenaccount() {
        return openaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.openAccount
     *
     * @param openaccount the value for htyw_orgization.openAccount
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setOpenaccount(String openaccount) {
        this.openaccount = openaccount == null ? null : openaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.showimage
     *
     * @return the value of htyw_orgization.showimage
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getShowimage() {
        return showimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.showimage
     *
     * @param showimage the value for htyw_orgization.showimage
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setShowimage(String showimage) {
        this.showimage = showimage == null ? null : showimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.sellArea2
     *
     * @return the value of htyw_orgization.sellArea2
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getSellarea2() {
        return sellarea2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.sellArea2
     *
     * @param sellarea2 the value for htyw_orgization.sellArea2
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setSellarea2(String sellarea2) {
        this.sellarea2 = sellarea2 == null ? null : sellarea2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.createtime
     *
     * @return the value of htyw_orgization.createtime
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.createtime
     *
     * @param createtime the value for htyw_orgization.createtime
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.recommendedent
     *
     * @return the value of htyw_orgization.recommendedent
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getRecommendedent() {
        return recommendedent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.recommendedent
     *
     * @param recommendedent the value for htyw_orgization.recommendedent
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setRecommendedent(String recommendedent) {
        this.recommendedent = recommendedent == null ? null : recommendedent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.qrcode
     *
     * @return the value of htyw_orgization.qrcode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.qrcode
     *
     * @param qrcode the value for htyw_orgization.qrcode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.orgtype
     *
     * @return the value of htyw_orgization.orgtype
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.orgtype
     *
     * @param orgtype the value for htyw_orgization.orgtype
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype == null ? null : orgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.filePath
     *
     * @return the value of htyw_orgization.filePath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.filePath
     *
     * @param filepath the value for htyw_orgization.filePath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.fileName
     *
     * @return the value of htyw_orgization.fileName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.fileName
     *
     * @param filename the value for htyw_orgization.fileName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.checkPersonAId
     *
     * @return the value of htyw_orgization.checkPersonAId
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCheckpersonaid() {
        return checkpersonaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.checkPersonAId
     *
     * @param checkpersonaid the value for htyw_orgization.checkPersonAId
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCheckpersonaid(String checkpersonaid) {
        this.checkpersonaid = checkpersonaid == null ? null : checkpersonaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.checkPersonAName
     *
     * @return the value of htyw_orgization.checkPersonAName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getCheckpersonaname() {
        return checkpersonaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.checkPersonAName
     *
     * @param checkpersonaname the value for htyw_orgization.checkPersonAName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setCheckpersonaname(String checkpersonaname) {
        this.checkpersonaname = checkpersonaname == null ? null : checkpersonaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.typename
     *
     * @return the value of htyw_orgization.typename
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.typename
     *
     * @param typename the value for htyw_orgization.typename
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.managetype
     *
     * @return the value of htyw_orgization.managetype
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getManagetype() {
        return managetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.managetype
     *
     * @param managetype the value for htyw_orgization.managetype
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setManagetype(String managetype) {
        this.managetype = managetype == null ? null : managetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bFactoryInnerName
     *
     * @return the value of htyw_orgization.b2bFactoryInnerName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bfactoryinnername() {
        return b2bfactoryinnername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bFactoryInnerName
     *
     * @param b2bfactoryinnername the value for htyw_orgization.b2bFactoryInnerName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bfactoryinnername(String b2bfactoryinnername) {
        this.b2bfactoryinnername = b2bfactoryinnername == null ? null : b2bfactoryinnername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bFactorySuperior
     *
     * @return the value of htyw_orgization.b2bFactorySuperior
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bfactorysuperior() {
        return b2bfactorysuperior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bFactorySuperior
     *
     * @param b2bfactorysuperior the value for htyw_orgization.b2bFactorySuperior
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bfactorysuperior(String b2bfactorysuperior) {
        this.b2bfactorysuperior = b2bfactorysuperior == null ? null : b2bfactorysuperior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bFactoryOpenBankAddress
     *
     * @return the value of htyw_orgization.b2bFactoryOpenBankAddress
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bfactoryopenbankaddress() {
        return b2bfactoryopenbankaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bFactoryOpenBankAddress
     *
     * @param b2bfactoryopenbankaddress the value for htyw_orgization.b2bFactoryOpenBankAddress
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bfactoryopenbankaddress(String b2bfactoryopenbankaddress) {
        this.b2bfactoryopenbankaddress = b2bfactoryopenbankaddress == null ? null : b2bfactoryopenbankaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bFactoryOpenAccountName
     *
     * @return the value of htyw_orgization.b2bFactoryOpenAccountName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bfactoryopenaccountname() {
        return b2bfactoryopenaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bFactoryOpenAccountName
     *
     * @param b2bfactoryopenaccountname the value for htyw_orgization.b2bFactoryOpenAccountName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bfactoryopenaccountname(String b2bfactoryopenaccountname) {
        this.b2bfactoryopenaccountname = b2bfactoryopenaccountname == null ? null : b2bfactoryopenaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bFactoryProductionAddress
     *
     * @return the value of htyw_orgization.b2bFactoryProductionAddress
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bfactoryproductionaddress() {
        return b2bfactoryproductionaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bFactoryProductionAddress
     *
     * @param b2bfactoryproductionaddress the value for htyw_orgization.b2bFactoryProductionAddress
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bfactoryproductionaddress(String b2bfactoryproductionaddress) {
        this.b2bfactoryproductionaddress = b2bfactoryproductionaddress == null ? null : b2bfactoryproductionaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bOrganizationCode
     *
     * @return the value of htyw_orgization.b2bOrganizationCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2borganizationcode() {
        return b2borganizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bOrganizationCode
     *
     * @param b2borganizationcode the value for htyw_orgization.b2bOrganizationCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2borganizationcode(String b2borganizationcode) {
        this.b2borganizationcode = b2borganizationcode == null ? null : b2borganizationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bOrganizationPath
     *
     * @return the value of htyw_orgization.b2bOrganizationPath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2borganizationpath() {
        return b2borganizationpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bOrganizationPath
     *
     * @param b2borganizationpath the value for htyw_orgization.b2bOrganizationPath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2borganizationpath(String b2borganizationpath) {
        this.b2borganizationpath = b2borganizationpath == null ? null : b2borganizationpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bBusinessLicenseCode
     *
     * @return the value of htyw_orgization.b2bBusinessLicenseCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bbusinesslicensecode() {
        return b2bbusinesslicensecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bBusinessLicenseCode
     *
     * @param b2bbusinesslicensecode the value for htyw_orgization.b2bBusinessLicenseCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bbusinesslicensecode(String b2bbusinesslicensecode) {
        this.b2bbusinesslicensecode = b2bbusinesslicensecode == null ? null : b2bbusinesslicensecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bBusinessLicensePath
     *
     * @return the value of htyw_orgization.b2bBusinessLicensePath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bbusinesslicensepath() {
        return b2bbusinesslicensepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bBusinessLicensePath
     *
     * @param b2bbusinesslicensepath the value for htyw_orgization.b2bBusinessLicensePath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bbusinesslicensepath(String b2bbusinesslicensepath) {
        this.b2bbusinesslicensepath = b2bbusinesslicensepath == null ? null : b2bbusinesslicensepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bNationalTaxCode
     *
     * @return the value of htyw_orgization.b2bNationalTaxCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bnationaltaxcode() {
        return b2bnationaltaxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bNationalTaxCode
     *
     * @param b2bnationaltaxcode the value for htyw_orgization.b2bNationalTaxCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bnationaltaxcode(String b2bnationaltaxcode) {
        this.b2bnationaltaxcode = b2bnationaltaxcode == null ? null : b2bnationaltaxcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bNationalTaxPath
     *
     * @return the value of htyw_orgization.b2bNationalTaxPath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bnationaltaxpath() {
        return b2bnationaltaxpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bNationalTaxPath
     *
     * @param b2bnationaltaxpath the value for htyw_orgization.b2bNationalTaxPath
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bnationaltaxpath(String b2bnationaltaxpath) {
        this.b2bnationaltaxpath = b2bnationaltaxpath == null ? null : b2bnationaltaxpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bUpdateDate
     *
     * @return the value of htyw_orgization.b2bUpdateDate
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bupdatedate() {
        return b2bupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bUpdateDate
     *
     * @param b2bupdatedate the value for htyw_orgization.b2bUpdateDate
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bupdatedate(String b2bupdatedate) {
        this.b2bupdatedate = b2bupdatedate == null ? null : b2bupdatedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bParentCode
     *
     * @return the value of htyw_orgization.b2bParentCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bparentcode() {
        return b2bparentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bParentCode
     *
     * @param b2bparentcode the value for htyw_orgization.b2bParentCode
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bparentcode(String b2bparentcode) {
        this.b2bparentcode = b2bparentcode == null ? null : b2bparentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bParentName
     *
     * @return the value of htyw_orgization.b2bParentName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bparentname() {
        return b2bparentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bParentName
     *
     * @param b2bparentname the value for htyw_orgization.b2bParentName
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bparentname(String b2bparentname) {
        this.b2bparentname = b2bparentname == null ? null : b2bparentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.b2bManagementLevel
     *
     * @return the value of htyw_orgization.b2bManagementLevel
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getB2bmanagementlevel() {
        return b2bmanagementlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.b2bManagementLevel
     *
     * @param b2bmanagementlevel the value for htyw_orgization.b2bManagementLevel
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setB2bmanagementlevel(String b2bmanagementlevel) {
        this.b2bmanagementlevel = b2bmanagementlevel == null ? null : b2bmanagementlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.businessType
     *
     * @return the value of htyw_orgization.businessType
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.businessType
     *
     * @param businesstype the value for htyw_orgization.businessType
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype == null ? null : businesstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.specialLine
     *
     * @return the value of htyw_orgization.specialLine
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getSpecialline() {
        return specialline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.specialLine
     *
     * @param specialline the value for htyw_orgization.specialLine
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setSpecialline(String specialline) {
        this.specialline = specialline == null ? null : specialline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column htyw_orgization.updatetime
     *
     * @return the value of htyw_orgization.updatetime
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column htyw_orgization.updatetime
     *
     * @param updatetime the value for htyw_orgization.updatetime
     * @mbg.generated Mon Nov 05 15:13:47 CST 2018
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}