package com.casic.oarp.datavisual.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScCreditFivescoreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public ScCreditFivescoreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScCreditFivescoreIdIsNull() {
            addCriterion("sc_credit_fivescore_id is null");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdIsNotNull() {
            addCriterion("sc_credit_fivescore_id is not null");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdEqualTo(String value) {
            addCriterion("sc_credit_fivescore_id =", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdNotEqualTo(String value) {
            addCriterion("sc_credit_fivescore_id <>", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdGreaterThan(String value) {
            addCriterion("sc_credit_fivescore_id >", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdGreaterThanOrEqualTo(String value) {
            addCriterion("sc_credit_fivescore_id >=", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdLessThan(String value) {
            addCriterion("sc_credit_fivescore_id <", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdLessThanOrEqualTo(String value) {
            addCriterion("sc_credit_fivescore_id <=", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdLike(String value) {
            addCriterion("sc_credit_fivescore_id like", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdNotLike(String value) {
            addCriterion("sc_credit_fivescore_id not like", value, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdIn(List<String> values) {
            addCriterion("sc_credit_fivescore_id in", values, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdNotIn(List<String> values) {
            addCriterion("sc_credit_fivescore_id not in", values, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdBetween(String value1, String value2) {
            addCriterion("sc_credit_fivescore_id between", value1, value2, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andScCreditFivescoreIdNotBetween(String value1, String value2) {
            addCriterion("sc_credit_fivescore_id not between", value1, value2, "scCreditFivescoreId");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidIsNull() {
            addCriterion("org_credit_quantid is null");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidIsNotNull() {
            addCriterion("org_credit_quantid is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidEqualTo(String value) {
            addCriterion("org_credit_quantid =", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidNotEqualTo(String value) {
            addCriterion("org_credit_quantid <>", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidGreaterThan(String value) {
            addCriterion("org_credit_quantid >", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidGreaterThanOrEqualTo(String value) {
            addCriterion("org_credit_quantid >=", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidLessThan(String value) {
            addCriterion("org_credit_quantid <", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidLessThanOrEqualTo(String value) {
            addCriterion("org_credit_quantid <=", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidLike(String value) {
            addCriterion("org_credit_quantid like", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidNotLike(String value) {
            addCriterion("org_credit_quantid not like", value, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidIn(List<String> values) {
            addCriterion("org_credit_quantid in", values, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidNotIn(List<String> values) {
            addCriterion("org_credit_quantid not in", values, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidBetween(String value1, String value2) {
            addCriterion("org_credit_quantid between", value1, value2, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrgCreditQuantidNotBetween(String value1, String value2) {
            addCriterion("org_credit_quantid not between", value1, value2, "orgCreditQuantid");
            return (Criteria) this;
        }

        public Criteria andOrginidIsNull() {
            addCriterion("orginid is null");
            return (Criteria) this;
        }

        public Criteria andOrginidIsNotNull() {
            addCriterion("orginid is not null");
            return (Criteria) this;
        }

        public Criteria andOrginidEqualTo(String value) {
            addCriterion("orginid =", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotEqualTo(String value) {
            addCriterion("orginid <>", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidGreaterThan(String value) {
            addCriterion("orginid >", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidGreaterThanOrEqualTo(String value) {
            addCriterion("orginid >=", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidLessThan(String value) {
            addCriterion("orginid <", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidLessThanOrEqualTo(String value) {
            addCriterion("orginid <=", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidLike(String value) {
            addCriterion("orginid like", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotLike(String value) {
            addCriterion("orginid not like", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidIn(List<String> values) {
            addCriterion("orginid in", values, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotIn(List<String> values) {
            addCriterion("orginid not in", values, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidBetween(String value1, String value2) {
            addCriterion("orginid between", value1, value2, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotBetween(String value1, String value2) {
            addCriterion("orginid not between", value1, value2, "orginid");
            return (Criteria) this;
        }

        public Criteria andPromisescoreIsNull() {
            addCriterion("promisescore is null");
            return (Criteria) this;
        }

        public Criteria andPromisescoreIsNotNull() {
            addCriterion("promisescore is not null");
            return (Criteria) this;
        }

        public Criteria andPromisescoreEqualTo(BigDecimal value) {
            addCriterion("promisescore =", value, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreNotEqualTo(BigDecimal value) {
            addCriterion("promisescore <>", value, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreGreaterThan(BigDecimal value) {
            addCriterion("promisescore >", value, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("promisescore >=", value, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreLessThan(BigDecimal value) {
            addCriterion("promisescore <", value, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("promisescore <=", value, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreIn(List<BigDecimal> values) {
            addCriterion("promisescore in", values, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreNotIn(List<BigDecimal> values) {
            addCriterion("promisescore not in", values, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promisescore between", value1, value2, "promisescore");
            return (Criteria) this;
        }

        public Criteria andPromisescoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promisescore not between", value1, value2, "promisescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreIsNull() {
            addCriterion("managescore is null");
            return (Criteria) this;
        }

        public Criteria andManagescoreIsNotNull() {
            addCriterion("managescore is not null");
            return (Criteria) this;
        }

        public Criteria andManagescoreEqualTo(BigDecimal value) {
            addCriterion("managescore =", value, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreNotEqualTo(BigDecimal value) {
            addCriterion("managescore <>", value, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreGreaterThan(BigDecimal value) {
            addCriterion("managescore >", value, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("managescore >=", value, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreLessThan(BigDecimal value) {
            addCriterion("managescore <", value, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("managescore <=", value, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreIn(List<BigDecimal> values) {
            addCriterion("managescore in", values, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreNotIn(List<BigDecimal> values) {
            addCriterion("managescore not in", values, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("managescore between", value1, value2, "managescore");
            return (Criteria) this;
        }

        public Criteria andManagescoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("managescore not between", value1, value2, "managescore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreIsNull() {
            addCriterion("specialityscore is null");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreIsNotNull() {
            addCriterion("specialityscore is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreEqualTo(BigDecimal value) {
            addCriterion("specialityscore =", value, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreNotEqualTo(BigDecimal value) {
            addCriterion("specialityscore <>", value, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreGreaterThan(BigDecimal value) {
            addCriterion("specialityscore >", value, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("specialityscore >=", value, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreLessThan(BigDecimal value) {
            addCriterion("specialityscore <", value, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("specialityscore <=", value, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreIn(List<BigDecimal> values) {
            addCriterion("specialityscore in", values, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreNotIn(List<BigDecimal> values) {
            addCriterion("specialityscore not in", values, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("specialityscore between", value1, value2, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andSpecialityscoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("specialityscore not between", value1, value2, "specialityscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreIsNull() {
            addCriterion("chainscore is null");
            return (Criteria) this;
        }

        public Criteria andChainscoreIsNotNull() {
            addCriterion("chainscore is not null");
            return (Criteria) this;
        }

        public Criteria andChainscoreEqualTo(BigDecimal value) {
            addCriterion("chainscore =", value, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreNotEqualTo(BigDecimal value) {
            addCriterion("chainscore <>", value, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreGreaterThan(BigDecimal value) {
            addCriterion("chainscore >", value, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("chainscore >=", value, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreLessThan(BigDecimal value) {
            addCriterion("chainscore <", value, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("chainscore <=", value, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreIn(List<BigDecimal> values) {
            addCriterion("chainscore in", values, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreNotIn(List<BigDecimal> values) {
            addCriterion("chainscore not in", values, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("chainscore between", value1, value2, "chainscore");
            return (Criteria) this;
        }

        public Criteria andChainscoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("chainscore not between", value1, value2, "chainscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreIsNull() {
            addCriterion("taxscore is null");
            return (Criteria) this;
        }

        public Criteria andTaxscoreIsNotNull() {
            addCriterion("taxscore is not null");
            return (Criteria) this;
        }

        public Criteria andTaxscoreEqualTo(BigDecimal value) {
            addCriterion("taxscore =", value, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreNotEqualTo(BigDecimal value) {
            addCriterion("taxscore <>", value, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreGreaterThan(BigDecimal value) {
            addCriterion("taxscore >", value, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("taxscore >=", value, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreLessThan(BigDecimal value) {
            addCriterion("taxscore <", value, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("taxscore <=", value, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreIn(List<BigDecimal> values) {
            addCriterion("taxscore in", values, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreNotIn(List<BigDecimal> values) {
            addCriterion("taxscore not in", values, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("taxscore between", value1, value2, "taxscore");
            return (Criteria) this;
        }

        public Criteria andTaxscoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("taxscore not between", value1, value2, "taxscore");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("orgname is null");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("orgname is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("orgname =", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("orgname <>", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("orgname >", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("orgname >=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("orgname <", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("orgname <=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("orgname like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("orgname not like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("orgname in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("orgname not in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("orgname between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("orgname not between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andAssesstimeIsNull() {
            addCriterion("assesstime is null");
            return (Criteria) this;
        }

        public Criteria andAssesstimeIsNotNull() {
            addCriterion("assesstime is not null");
            return (Criteria) this;
        }

        public Criteria andAssesstimeEqualTo(Date value) {
            addCriterion("assesstime =", value, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeNotEqualTo(Date value) {
            addCriterion("assesstime <>", value, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeGreaterThan(Date value) {
            addCriterion("assesstime >", value, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeGreaterThanOrEqualTo(Date value) {
            addCriterion("assesstime >=", value, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeLessThan(Date value) {
            addCriterion("assesstime <", value, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeLessThanOrEqualTo(Date value) {
            addCriterion("assesstime <=", value, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeIn(List<Date> values) {
            addCriterion("assesstime in", values, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeNotIn(List<Date> values) {
            addCriterion("assesstime not in", values, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeBetween(Date value1, Date value2) {
            addCriterion("assesstime between", value1, value2, "assesstime");
            return (Criteria) this;
        }

        public Criteria andAssesstimeNotBetween(Date value1, Date value2) {
            addCriterion("assesstime not between", value1, value2, "assesstime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 19 10:33:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}