package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ScCreditFivescore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.sc_credit_fivescore_id
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private String scCreditFivescoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.org_credit_quantid
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private String orgCreditQuantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.orginid
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private String orginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.promisescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private BigDecimal promisescore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.managescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private BigDecimal managescore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.specialityscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private BigDecimal specialityscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.chainscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private BigDecimal chainscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.taxscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private BigDecimal taxscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.orgname
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_credit_fivescore.assesstime
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private Date assesstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_credit_fivescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.sc_credit_fivescore_id
     *
     * @return the value of sc_credit_fivescore.sc_credit_fivescore_id
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public String getScCreditFivescoreId() {
        return scCreditFivescoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.sc_credit_fivescore_id
     *
     * @param scCreditFivescoreId the value for sc_credit_fivescore.sc_credit_fivescore_id
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setScCreditFivescoreId(String scCreditFivescoreId) {
        this.scCreditFivescoreId = scCreditFivescoreId == null ? null : scCreditFivescoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.org_credit_quantid
     *
     * @return the value of sc_credit_fivescore.org_credit_quantid
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public String getOrgCreditQuantid() {
        return orgCreditQuantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.org_credit_quantid
     *
     * @param orgCreditQuantid the value for sc_credit_fivescore.org_credit_quantid
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setOrgCreditQuantid(String orgCreditQuantid) {
        this.orgCreditQuantid = orgCreditQuantid == null ? null : orgCreditQuantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.orginid
     *
     * @return the value of sc_credit_fivescore.orginid
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public String getOrginid() {
        return orginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.orginid
     *
     * @param orginid the value for sc_credit_fivescore.orginid
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setOrginid(String orginid) {
        this.orginid = orginid == null ? null : orginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.promisescore
     *
     * @return the value of sc_credit_fivescore.promisescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public BigDecimal getPromisescore() {
        return promisescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.promisescore
     *
     * @param promisescore the value for sc_credit_fivescore.promisescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setPromisescore(BigDecimal promisescore) {
        this.promisescore = promisescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.managescore
     *
     * @return the value of sc_credit_fivescore.managescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public BigDecimal getManagescore() {
        return managescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.managescore
     *
     * @param managescore the value for sc_credit_fivescore.managescore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setManagescore(BigDecimal managescore) {
        this.managescore = managescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.specialityscore
     *
     * @return the value of sc_credit_fivescore.specialityscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public BigDecimal getSpecialityscore() {
        return specialityscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.specialityscore
     *
     * @param specialityscore the value for sc_credit_fivescore.specialityscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setSpecialityscore(BigDecimal specialityscore) {
        this.specialityscore = specialityscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.chainscore
     *
     * @return the value of sc_credit_fivescore.chainscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public BigDecimal getChainscore() {
        return chainscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.chainscore
     *
     * @param chainscore the value for sc_credit_fivescore.chainscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setChainscore(BigDecimal chainscore) {
        this.chainscore = chainscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.taxscore
     *
     * @return the value of sc_credit_fivescore.taxscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public BigDecimal getTaxscore() {
        return taxscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.taxscore
     *
     * @param taxscore the value for sc_credit_fivescore.taxscore
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setTaxscore(BigDecimal taxscore) {
        this.taxscore = taxscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.orgname
     *
     * @return the value of sc_credit_fivescore.orgname
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.orgname
     *
     * @param orgname the value for sc_credit_fivescore.orgname
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_credit_fivescore.assesstime
     *
     * @return the value of sc_credit_fivescore.assesstime
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public Date getAssesstime() {
        return assesstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_credit_fivescore.assesstime
     *
     * @param assesstime the value for sc_credit_fivescore.assesstime
     *
     * @mbg.generated Mon Nov 19 10:33:28 CST 2018
     */
    public void setAssesstime(Date assesstime) {
        this.assesstime = assesstime;
    }
}