package com.casic.oarp.datavisual.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScwarnsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    protected String orderByClause;
//    protected Integer startRow;
//    protected Integer pageSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public ScwarnsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWarnIdIsNull() {
            addCriterion("warn_id is null");
            return (Criteria) this;
        }

        public Criteria andWarnIdIsNotNull() {
            addCriterion("warn_id is not null");
            return (Criteria) this;
        }

        public Criteria andWarnIdEqualTo(String value) {
            addCriterion("warn_id =", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdNotEqualTo(String value) {
            addCriterion("warn_id <>", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdGreaterThan(String value) {
            addCriterion("warn_id >", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdGreaterThanOrEqualTo(String value) {
            addCriterion("warn_id >=", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdLessThan(String value) {
            addCriterion("warn_id <", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdLessThanOrEqualTo(String value) {
            addCriterion("warn_id <=", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdLike(String value) {
            addCriterion("warn_id like", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdNotLike(String value) {
            addCriterion("warn_id not like", value, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdIn(List<String> values) {
            addCriterion("warn_id in", values, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdNotIn(List<String> values) {
            addCriterion("warn_id not in", values, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdBetween(String value1, String value2) {
            addCriterion("warn_id between", value1, value2, "warnId");
            return (Criteria) this;
        }

        public Criteria andWarnIdNotBetween(String value1, String value2) {
            addCriterion("warn_id not between", value1, value2, "warnId");
            return (Criteria) this;
        }

        public Criteria andOrginidIsNull() {
            addCriterion("orginid is null");
            return (Criteria) this;
        }

        public Criteria andOrginidIsNotNull() {
            addCriterion("orginid is not null");
            return (Criteria) this;
        }

        public Criteria andOrginidEqualTo(String value) {
            addCriterion("orginid =", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotEqualTo(String value) {
            addCriterion("orginid <>", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidGreaterThan(String value) {
            addCriterion("orginid >", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidGreaterThanOrEqualTo(String value) {
            addCriterion("orginid >=", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidLessThan(String value) {
            addCriterion("orginid <", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidLessThanOrEqualTo(String value) {
            addCriterion("orginid <=", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidLike(String value) {
            addCriterion("orginid like", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotLike(String value) {
            addCriterion("orginid not like", value, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidIn(List<String> values) {
            addCriterion("orginid in", values, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotIn(List<String> values) {
            addCriterion("orginid not in", values, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidBetween(String value1, String value2) {
            addCriterion("orginid between", value1, value2, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrginidNotBetween(String value1, String value2) {
            addCriterion("orginid not between", value1, value2, "orginid");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("orgname is null");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("orgname is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("orgname =", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("orgname <>", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("orgname >", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("orgname >=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("orgname <", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("orgname <=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("orgname like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("orgname not like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("orgname in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("orgname not in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("orgname between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("orgname not between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("parentid is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("parentid is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(String value) {
            addCriterion("parentid =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(String value) {
            addCriterion("parentid <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(String value) {
            addCriterion("parentid >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(String value) {
            addCriterion("parentid >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(String value) {
            addCriterion("parentid <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(String value) {
            addCriterion("parentid <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLike(String value) {
            addCriterion("parentid like", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotLike(String value) {
            addCriterion("parentid not like", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<String> values) {
            addCriterion("parentid in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<String> values) {
            addCriterion("parentid not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(String value1, String value2) {
            addCriterion("parentid between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(String value1, String value2) {
            addCriterion("parentid not between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andWarnmessageIsNull() {
            addCriterion("warnmessage is null");
            return (Criteria) this;
        }

        public Criteria andWarnmessageIsNotNull() {
            addCriterion("warnmessage is not null");
            return (Criteria) this;
        }

        public Criteria andWarnmessageEqualTo(String value) {
            addCriterion("warnmessage =", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageNotEqualTo(String value) {
            addCriterion("warnmessage <>", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageGreaterThan(String value) {
            addCriterion("warnmessage >", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageGreaterThanOrEqualTo(String value) {
            addCriterion("warnmessage >=", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageLessThan(String value) {
            addCriterion("warnmessage <", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageLessThanOrEqualTo(String value) {
            addCriterion("warnmessage <=", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageLike(String value) {
            addCriterion("warnmessage like", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageNotLike(String value) {
            addCriterion("warnmessage not like", value, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageIn(List<String> values) {
            addCriterion("warnmessage in", values, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageNotIn(List<String> values) {
            addCriterion("warnmessage not in", values, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageBetween(String value1, String value2) {
            addCriterion("warnmessage between", value1, value2, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarnmessageNotBetween(String value1, String value2) {
            addCriterion("warnmessage not between", value1, value2, "warnmessage");
            return (Criteria) this;
        }

        public Criteria andWarntimeIsNull() {
            addCriterion("warntime is null");
            return (Criteria) this;
        }

        public Criteria andWarntimeIsNotNull() {
            addCriterion("warntime is not null");
            return (Criteria) this;
        }

        public Criteria andWarntimeEqualTo(Date value) {
            addCriterion("warntime =", value, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeNotEqualTo(Date value) {
            addCriterion("warntime <>", value, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeGreaterThan(Date value) {
            addCriterion("warntime >", value, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("warntime >=", value, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeLessThan(Date value) {
            addCriterion("warntime <", value, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeLessThanOrEqualTo(Date value) {
            addCriterion("warntime <=", value, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeIn(List<Date> values) {
            addCriterion("warntime in", values, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeNotIn(List<Date> values) {
            addCriterion("warntime not in", values, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeBetween(Date value1, Date value2) {
            addCriterion("warntime between", value1, value2, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntimeNotBetween(Date value1, Date value2) {
            addCriterion("warntime not between", value1, value2, "warntime");
            return (Criteria) this;
        }

        public Criteria andWarntypeIsNull() {
            addCriterion("warntype is null");
            return (Criteria) this;
        }

        public Criteria andWarntypeIsNotNull() {
            addCriterion("warntype is not null");
            return (Criteria) this;
        }

        public Criteria andWarntypeEqualTo(String value) {
            addCriterion("warntype =", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotEqualTo(String value) {
            addCriterion("warntype <>", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeGreaterThan(String value) {
            addCriterion("warntype >", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeGreaterThanOrEqualTo(String value) {
            addCriterion("warntype >=", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeLessThan(String value) {
            addCriterion("warntype <", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeLessThanOrEqualTo(String value) {
            addCriterion("warntype <=", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeLike(String value) {
            addCriterion("warntype like", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotLike(String value) {
            addCriterion("warntype not like", value, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeIn(List<String> values) {
            addCriterion("warntype in", values, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotIn(List<String> values) {
            addCriterion("warntype not in", values, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeBetween(String value1, String value2) {
            addCriterion("warntype between", value1, value2, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarntypeNotBetween(String value1, String value2) {
            addCriterion("warntype not between", value1, value2, "warntype");
            return (Criteria) this;
        }

        public Criteria andWarnnameIsNull() {
            addCriterion("warnname is null");
            return (Criteria) this;
        }

        public Criteria andWarnnameIsNotNull() {
            addCriterion("warnname is not null");
            return (Criteria) this;
        }

        public Criteria andWarnnameEqualTo(String value) {
            addCriterion("warnname =", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotEqualTo(String value) {
            addCriterion("warnname <>", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameGreaterThan(String value) {
            addCriterion("warnname >", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameGreaterThanOrEqualTo(String value) {
            addCriterion("warnname >=", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameLessThan(String value) {
            addCriterion("warnname <", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameLessThanOrEqualTo(String value) {
            addCriterion("warnname <=", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameLike(String value) {
            addCriterion("warnname like", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotLike(String value) {
            addCriterion("warnname not like", value, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameIn(List<String> values) {
            addCriterion("warnname in", values, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotIn(List<String> values) {
            addCriterion("warnname not in", values, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameBetween(String value1, String value2) {
            addCriterion("warnname between", value1, value2, "warnname");
            return (Criteria) this;
        }

        public Criteria andWarnnameNotBetween(String value1, String value2) {
            addCriterion("warnname not between", value1, value2, "warnname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_warns
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 19 10:31:15 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}