package com.casic.oarp.datavisual.po;

import java.io.Serializable;
import java.util.Date;

public class Scwarns implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.warn_id
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String warnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.orginid
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String orginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.orgname
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.parentid
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.warnmessage
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String warnmessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.warntime
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private Date warntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.warntype
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String warntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_warns.warnname
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private String warnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sc_warns
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.warn_id
     *
     * @return the value of sc_warns.warn_id
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getWarnId() {
        return warnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.warn_id
     *
     * @param warnId the value for sc_warns.warn_id
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setWarnId(String warnId) {
        this.warnId = warnId == null ? null : warnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.orginid
     *
     * @return the value of sc_warns.orginid
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getOrginid() {
        return orginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.orginid
     *
     * @param orginid the value for sc_warns.orginid
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setOrginid(String orginid) {
        this.orginid = orginid == null ? null : orginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.orgname
     *
     * @return the value of sc_warns.orgname
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.orgname
     *
     * @param orgname the value for sc_warns.orgname
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.parentid
     *
     * @return the value of sc_warns.parentid
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.parentid
     *
     * @param parentid the value for sc_warns.parentid
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.warnmessage
     *
     * @return the value of sc_warns.warnmessage
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getWarnmessage() {
        return warnmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.warnmessage
     *
     * @param warnmessage the value for sc_warns.warnmessage
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setWarnmessage(String warnmessage) {
        this.warnmessage = warnmessage == null ? null : warnmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.warntime
     *
     * @return the value of sc_warns.warntime
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public Date getWarntime() {
        return warntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.warntime
     *
     * @param warntime the value for sc_warns.warntime
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setWarntime(Date warntime) {
        this.warntime = warntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.warntype
     *
     * @return the value of sc_warns.warntype
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getWarntype() {
        return warntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.warntype
     *
     * @param warntype the value for sc_warns.warntype
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setWarntype(String warntype) {
        this.warntype = warntype == null ? null : warntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_warns.warnname
     *
     * @return the value of sc_warns.warnname
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public String getWarnname() {
        return warnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_warns.warnname
     *
     * @param warnname the value for sc_warns.warnname
     *
     * @mbg.generated Mon Nov 19 10:31:15 CST 2018
     */
    public void setWarnname(String warnname) {
        this.warnname = warnname == null ? null : warnname.trim();
    }
}